<?php

declare(strict_types=1);

return [
    'admin-settings' => [
        'page'    => 'marketing-admin',
        'form'    => 'Settings',
        'open'    => ['marketing-admin', '?tab=settings'],
        'who'     => 'Marketing admin (full Marketing access)',
        'purpose' => 'One box per setting, listed A–Z by key, with its description underneath. These values steer harvesting, AI scoring and writing, the claims check, the calendar, engagement scores, the site audit and alerts. Scheduled jobs pick up a change on their next run; portal pages use it straight away.',
        'note'    => '**Save settings** saves only the boxes you changed, keeps each change in the audit log and reports how many were updated. Nothing is checked on save – a typo is saved as typed. Lists are one entry per line. For numbers type digits only: depending on where it is read, a blank box or a word counts as 0, which can switch a limit off. On the **Jobs** tab, **Run now** starts a scheduled job straight away and shows its result at the top of the page; jobs marked “Runs on demand from its module” are started from their own screens. API keys are not stored here.',
        'fields'  => [
            [
                'field' => 'ai.anthropic.model',
                'enter' => 'The Claude model id to use when a prompt in Prompt Lab leaves **Model** blank. Seeded as **claude-sonnet-4-5**.',
                'now'   => 'Used by every Anthropic prompt with a blank model – as shipped, every prompt except item scoring and response triage, which name Claude Haiku.',
                'later' => 'Its calls are costed with the rates in ai.pricing.',
                'watch' => 'Use the exact id from Anthropic; a wrong id makes those AI calls fail. Add the model to ai.pricing too, or its calls are logged at $0 and the budget never sees them.',
            ],
            [
                'field' => 'ai.default_provider',
                'enter' => '**anthropic** or **openai**.',
                'now'   => 'Not used at the moment – each prompt picks its own provider in Prompt Lab.',
                'later' => '—',
                'watch' => 'Changing it has no effect. Switch a prompt’s provider in Prompt Lab instead.',
            ],
            [
                'field' => 'ai.monthly_budget_usd',
                'enter' => 'A dollar amount, e.g. **150**. 0 means no limit.',
                'now'   => 'Before every AI call – scheduled or on demand – the month-to-date AI cost (UTC month) is checked. Once it reaches this amount the call is refused with “Monthly AI budget reached”.',
                'later' => 'Drives the budget bar, forecast and runway on the AI & API Usage tab, and the ai_budget alert (warning at alerts.budget_warn_pct, high alert when reached).',
                'watch' => 'Blank or 0 removes the limit and the budget alert. Raising it mid-month unblocks new calls, but nothing reruns by itself – rerun what failed.',
            ],
            [
                'field' => 'ai.openai.model',
                'enter' => 'The OpenAI model id used when a prompt set to OpenAI leaves **Model** blank. Seeded as **gpt-5-mini**.',
                'now'   => 'Only used by prompts switched to OpenAI in Prompt Lab – none are, as shipped.',
                'later' => '—',
                'watch' => 'Use the exact id and add it to ai.pricing, as for ai.anthropic.model.',
            ],
            [
                'field' => 'ai.pricing',
                'enter' => 'One line of JSON: each model id with its price in dollars per million tokens, e.g. {"claude-haiku-4-5":{"in":1,"out":5}}. An optional "web_search" entry sets the price per web search (otherwise $0.01).',
                'now'   => 'Every AI call’s cost is estimated from its token counts with these rates. A model matches its exact id, or the first entry its id starts with. Scoring batches are costed at half price.',
                'later' => 'All spend figures, the monthly budget check and the ai_budget alert use these estimates.',
                'watch' => 'Broken JSON (a missing quote, comma or brace) makes every cost $0, so the budget stops working – copy the current value before editing. A model not listed is also costed at $0. Update rates when a provider changes its prices.',
            ],
            [
                'field' => 'alerts.budget_warn_pct',
                'enter' => 'A percentage, seeded **80**.',
                'now'   => 'The daily alerts check warns when month-to-date AI spend reaches this share of ai.monthly_budget_usd, or when the month-end forecast passes the budget.',
                'later' => 'Reaching the budget itself is a separate high alert.',
                'watch' => 'Only works while **ai_budget** is listed in alerts.rules and a budget is set.',
            ],
            [
                'field' => 'alerts.recipients',
                'enter' => 'Email addresses, one per line. Blank as shipped.',
                'now'   => 'New alerts from the daily check are emailed to these addresses. Lines without an @ are ignored.',
                'later' => 'Listed on Audit & Issues → Alerts.',
                'watch' => 'Blank sends alerts to the login email of everyone with full Marketing access – check that is who you want.',
            ],
            [
                'field' => 'alerts.rules',
                'enter' => 'The alert rules that are on, one per line: **job_failed**, **traffic_drop**, **legacy_brand**, **site_error**, **escalation_overdue**, **ai_budget**, **rank_drop**.',
                'now'   => 'The daily alerts check (about 06:00 Central) tests only the rules listed. Removing a rule resolves its open alerts on the next run.',
                'later' => 'Shown on Audit & Issues → Alerts; new alerts are emailed to alerts.recipients.',
                'watch' => 'Spell the names exactly – unknown lines are ignored without warning.',
            ],
            [
                'field' => 'alerts.traffic_drop_pct',
                'enter' => 'A percentage, seeded **30**.',
                'now'   => 'traffic_drop fires when the last 7 days of GA4 sessions, or of Search Console clicks, fall this far below the weekly average of the 4 weeks before.',
                'later' => '—',
                'watch' => 'A lower number means more alerts on normal week-to-week swings.',
            ],
            [
                'field' => 'alerts.traffic_min_clicks',
                'enter' => 'Clicks per week, seeded **50**.',
                'now'   => 'The Search Console half of traffic_drop stays quiet unless the 4-week baseline has at least this many clicks a week.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'alerts.traffic_min_sessions',
                'enter' => 'GA4 sessions per week, seeded **100**.',
                'now'   => 'The GA4 half of traffic_drop stays quiet unless the 4-week baseline has at least this many sessions a week.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'analytics.allowed_host',
                'enter' => 'The site’s domain without www, seeded **nutraaxislabs.com**.',
                'now'   => 'The nightly Search Console and GA4 loads refuse to run if the connected property is not on this domain. Also the fallback site address when pages.site_url is blank.',
                'later' => '—',
                'watch' => 'A safety lock against loading another site’s data – change it only if the site really moves domain.',
            ],
            [
                'field' => 'backlinks.spam_threshold',
                'enter' => 'A spam score from 0 to 100, seeded **30**.',
                'now'   => 'Backlinks & Outreach flags links from domains scoring this or more (score from the OpenRush import) as likely spam, counts them in the banner, and offers them on the Disavow tab.',
                'later' => '—',
                'watch' => 'Semrush backlink exports carry no spam score, so their links are never flagged.',
            ],
            [
                'field' => 'blog.author',
                'enter' => 'The default byline, seeded **NutraAxis Team**. Keep it under 150 characters.',
                'now'   => 'Used as the author when a piece is published to the blog with the author box left blank.',
                'later' => 'Shown on each blog post.',
                'watch' => 'Posts already published keep their byline until they are published again.',
            ],
            [
                'field' => 'blog.page_url',
                'enter' => 'The full public address of the blog page, seeded **https://nutraaxislabs.com/our-blog**.',
                'now'   => 'Each post’s live link is this address plus ?post= and the post address. Shown on the blog publish form and sent to the website with the posts.',
                'later' => '—',
                'watch' => 'Must match the real blog page in Adobe DA. Changing it changes every post’s link; links already shared keep pointing at the old address.',
            ],
            [
                'field' => 'brand.audiences',
                'enter' => 'One audience per line: key|description. Seeded **practitioner|Healthcare practitioners and clinic owners** and **consumer|Health-conscious adults buying through a practitioner**.',
                'now'   => 'Fills the **Audience** list on interests. When the AI writes or revises campaigns and content, it is given the description for the chosen audience (both lines for **Both**).',
                'later' => 'The research agent is told each interest’s audience.',
                'watch' => 'Keep the keys **practitioner** and **consumer** – campaigns and content choose from those two (or Both). With a renamed key the AI gets every description instead of the right one.',
            ],
            [
                'field' => 'brand.competitors',
                'enter' => 'Competitor company names or domains, one per line. Blank as shipped.',
                'now'   => 'Given to the scoring AI, which tags items about these companies as **competitor** evidence.',
                'later' => 'The evidence type shows on items and topics.',
                'watch' => 'While blank, the scoring AI is told “none listed” and has to judge competitor items on its own.',
            ],
            [
                'field' => 'brand.legacy_allow_paths',
                'enter' => 'Page paths allowed to mention the old names, one per line, e.g. **/nutrasync-landing**. A path covers the page and anything below it; start a line with ^ for a pattern.',
                'now'   => 'The site crawl skips the legacy-name check on these pages.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'brand.legacy_terms',
                'enter' => 'Old or misspelled brand names, one per line. Seeded **NutraSync** and **NutrAxis**. Matched as whole words, any case.',
                'now'   => 'The weekly site crawl looks for them in each page’s text; a hit opens a legacy brand issue in Audit & Issues.',
                'later' => 'With **legacy_brand** in alerts.rules, each affected page also raises a high alert.',
                'watch' => 'Whole-word matching: “NutrAxis” does not match “NutraAxis”. Never list the current name.',
            ],
            [
                'field' => 'brand.name',
                'enter' => 'The brand name as it should appear in AI output, seeded **NutraAxis Labs**.',
                'now'   => 'Given to nearly every AI prompt: the research agent, scoring, clustering, campaign and content writing, the claims check, response triage, the Monday digest and fix specs.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'brand.site_url',
                'enter' => 'The site’s home address, seeded **https://nutraaxislabs.com**.',
                'now'   => 'The call-to-action link for a new campaign when campaign.default_cta_url is blank. Also the example address in the Content Pipeline’s URL boxes.',
                'later' => '—',
                'watch' => 'The site crawl and analytics use pages.site_url, not this.',
            ],
            [
                'field' => 'brand.terms',
                'enter' => 'Brand names, one per line.',
                'now'   => 'Not used at the moment – no job or page reads it.',
                'later' => '—',
                'watch' => 'To catch old names on the website, use brand.legacy_terms.',
            ],
            [
                'field' => 'brand.voice',
                'enter' => 'A few sentences on tone. Seeded “Evidence-led, practitioner-respectful, plain English. No hype, no disease claims, no guarantees.”',
                'now'   => 'Given to the AI when it writes and revises campaign assets, and when it writes briefs, drafts and revisions in the Content Pipeline.',
                'later' => '—',
                'watch' => 'Keep it short and concrete. Compliance rules belong in campaign.rules.',
            ],
            [
                'field' => 'calendar.default_times',
                'enter' => 'One line per channel: channel key|time, 24-hour Central time, e.g. **linkedin|08:30**.',
                'now'   => 'Used when a whole campaign is laid out on the calendar without a time, and to prefill the time when scheduling one asset. Listed on the Calendar’s Ready tab.',
                'later' => '—',
                'watch' => 'Channel keys must match campaign.channels. A channel with no line, or a badly typed time, falls back to 09:00.',
            ],
            [
                'field' => 'calendar.min_gap_hours',
                'enter' => 'Hours, seeded **20**.',
                'now'   => 'The calendar and the asset page warn when two scheduled assets on the same channel are closer together than this.',
                'later' => '—',
                'watch' => 'A warning only – it does not stop scheduling.',
            ],
            [
                'field' => 'campaign.channels',
                'enter' => 'One channel per line: key|label|medium|max characters|writing guidance. Medium is **social** or **email**; max 0 means no limit. Example: **facebook|Facebook|social|2000|Conversational; 60-150 words; up to 2 hashtags.**',
                'now'   => 'Sets the channels you can pick for a campaign and in the Response Inbox, their labels, the guidance and character limit given to the AI, and the length check in the claims check.',
                'later' => 'The key becomes utm_source and the medium utm_medium on every tracked link, which is how GA4 visits are matched to assets and scored.',
                'watch' => 'Don’t rename or delete a key that existing assets use – they lose their label, limit and tracking. The key **x** is special: [LINK] counts as 23 characters in its length check.',
            ],
            [
                'field' => 'campaign.default_cta_url',
                'enter' => 'A full http(s) address, seeded **https://nutraaxislabs.com**.',
                'now'   => 'Prefills the call-to-action URL on New campaign, and is used if that box is left blank (then brand.site_url if this is blank too).',
                'later' => 'Tracking tags are added to it per asset.',
                'watch' => '—',
            ],
            [
                'field' => 'campaign.rules',
                'enter' => 'Compliance rules, one per line, in plain sentences.',
                'now'   => 'Given as a bullet list to the AI when it writes or revises campaign assets, writes content briefs, drafts and revisions, and runs the claims check (as the house rules it scores against).',
                'later' => '—',
                'watch' => 'Change them only with compliance sign-off – they decide what the AI writes and what the check passes. The last seeded rule tells the AI to add the DSHEA disclaimer after ‡ claims; keep it.',
            ],
            [
                'field' => 'claims.disclaimer',
                'enter' => 'The full DSHEA disclaimer text.',
                'now'   => 'Given to the AI when it writes and revises campaign assets and content drafts, to add after product claims marked ‡. Shown on Claims Matrix → Claims check rules.',
                'later' => '—',
                'watch' => 'The portal does not add it by itself – the AI writes it in, and the claims check flags it when missing.',
            ],
            [
                'field' => 'claims.flag_terms',
                'enter' => 'Words and phrases, one per line, e.g. **cure**, **clinically proven**, **diabetes**. Matched as whole words or phrases, any case.',
                'now'   => 'In the claims check each term found takes 1 point off the AI’s score and sends the asset or piece to compliance review. In response triage a hit makes a response at least claims risk, which escalates it to compliance.',
                'later' => 'Listed on Claims Matrix → Claims check rules.',
                'watch' => 'Common words here push most copy below claims.min_score and into compliance. Terms match literally – list plural forms separately.',
            ],
            [
                'field' => 'claims.min_score',
                'enter' => 'A score from 0 to 10, seeded **7**.',
                'now'   => 'A campaign asset or content version needs at least this score in its latest claims check before it can be submitted for review.',
                'later' => 'Shown on asset, campaign and piece pages and on Claims Matrix → Claims check rules.',
                'watch' => 'Raising it blocks copy that passed before until it is revised. Type a number – a word is read as 0 and would let everything through.',
            ],
            [
                'field' => 'content.types',
                'enter' => 'One type per line: key|label|default words|guidance, e.g. **faq|FAQ page|700|Question-and-answer page targeting search questions…**',
                'now'   => 'Fills the **Type** list on New piece. The word count sets the default length and the guidance is given to the AI for the brief and draft.',
                'later' => '—',
                'watch' => 'Don’t rename or remove a key that pieces use – they lose their label and guidance. A blank word count means 1,200.',
            ],
            [
                'field' => 'engagement.adverse_terms',
                'enter' => 'Words, one per line, e.g. **side effect**, **rash**, **hospital**. Whole words, any case.',
                'now'   => 'Response triage labels any response containing one as a **possible adverse event**, whatever the AI said, and escalates it to compliance.',
                'later' => '—',
                'watch' => 'Err towards more terms – a miss means a possible adverse event may not reach compliance.',
            ],
            [
                'field' => 'engagement.digest_max_tasks',
                'enter' => 'A number from 0 to 10, seeded **5**.',
                'now'   => 'The most recommended tasks the Monday digest opens.',
                'later' => 'Shown on Engagement & Performance.',
                'watch' => '0 means the digest opens no tasks.',
            ],
            [
                'field' => 'engagement.escalation_hours',
                'enter' => 'Hours, at least 1, seeded **24**.',
                'now'   => 'Claims-risk and possible adverse-event responses get a compliance due time this many hours after triage.',
                'later' => 'Once that time passes, the escalation_overdue alert fires.',
                'watch' => 'Agree any change with compliance.',
            ],
            [
                'field' => 'engagement.half_points',
                'enter' => 'Points, seeded **40**.',
                'now'   => 'Nightly scoring: an asset’s score is 100 × points ÷ (points + this number), so an asset with this many points scores 50.',
                'later' => 'Scores roll up to campaigns, topics and interests.',
                'watch' => 'Changing it rescales every score from the next nightly run, so week-to-week comparisons jump.',
            ],
            [
                'field' => 'engagement.mature_days',
                'enter' => 'Days, seeded **7**.',
                'now'   => 'Assets and pieces posted fewer days ago than this get a low-confidence (“Early read”) score.',
                'later' => 'Low-confidence scores don’t count towards interest weights or suggested priorities.',
                'watch' => '—',
            ],
            [
                'field' => 'engagement.min_assets_for_weight',
                'enter' => 'A number, seeded **3**.',
                'now'   => 'An interest needs at least this many medium- or high-confidence asset scores before its relevance weight or suggested priority can move. At least two interests must qualify.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'engagement.weight_range',
                'enter' => 'A decimal from 0 to 0.5, seeded **0.2** (±20%). 0 turns weighting off.',
                'now'   => 'Nightly scoring sets each qualifying interest’s relevance weight between 1 minus and 1 plus this, depending on how it performs against the others.',
                'later' => 'The weight multiplies an item’s relevance for that interest when it is scored, so interests that perform well pull in more items.',
                'watch' => 'Values above 0.5 are treated as 0.5.',
            ],
            [
                'field' => 'engagement.weights',
                'enter' => 'Points per unit, one per line: metric|points, e.g. **key_event|10**. Metrics: session, engaged_session, key_event, transaction, lead, like, comment, share, save, link_click, email_open, email_click, email_reply, search_click, positive_response.',
                'now'   => 'Nightly scoring adds up each asset’s and piece’s points from GA4 visits, entered post and email metrics and responses, using these weights.',
                'later' => 'Feeds every engagement score, rollup, interest weight and the Monday digest.',
                'watch' => 'A metric left out scores nothing; a misspelled metric is ignored.',
            ],
            [
                'field' => 'ga4.backfill_days',
                'enter' => 'Days, seeded **90**.',
                'now'   => 'How much GA4 history the nightly load fetches on its first run.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'ga4.refresh_days',
                'enter' => 'Days, seeded **4**.',
                'now'   => 'Each nightly GA4 load reloads this many recent days, because GA4 finalises data within 48 hours.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'gsc.backfill_days',
                'enter' => 'Days, seeded **90**.',
                'now'   => 'How much Search Console history the nightly load fetches on its first run.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'gsc.refresh_days',
                'enter' => 'Days, seeded **5**.',
                'now'   => 'Each nightly Search Console load reloads this many recent days, because Search Console finalises data 2–3 days late.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'harvest.auto_pause_failures',
                'enter' => 'A number, seeded **5**.',
                'now'   => 'The harvester auto-pauses a source that fails this many runs in a row.',
                'later' => 'Auto-paused sources show on Interests & Sources until you fix and resume them.',
                'watch' => '—',
            ],
            [
                'field' => 'harvest.crawl_delay_ms',
                'enter' => 'Milliseconds, seeded **1500**.',
                'now'   => 'The pause between page fetches when the harvester crawls a site source.',
                'later' => '—',
                'watch' => 'Shorter pauses crawl faster but can get us blocked by the site.',
            ],
            [
                'field' => 'harvest.lookback_days',
                'enter' => 'Days, seeded **30**.',
                'now'   => 'PubMed and ClinicalTrials.gov sources only fetch records newer than this. The research agent is asked for items published within this many days.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'harvest.max_items_per_run',
                'enter' => 'A number, seeded **50**.',
                'now'   => 'The most items the harvester takes from one source in one run – feed entries, search results or crawled pages (site crawls also stop at the source’s own page limit).',
                'later' => '—',
                'watch' => 'A higher number means more items to score, and more AI spend.',
            ],
            [
                'field' => 'harvest.user_agent',
                'enter' => 'The name the harvester gives websites, with a contact link.',
                'now'   => 'Sent with every feed fetch and site-source crawl, when the research agent verifies its URLs, and when the portal fetches a manually added item’s title.',
                'later' => '—',
                'watch' => 'Keep a real contact address – site owners use it to reach us instead of blocking us.',
            ],
            [
                'field' => 'issues.platform_notes',
                'enter' => 'A paragraph on how the website is built and published.',
                'now'   => 'Given to the fix-spec AI so developer specs point to the right place (template, block, page metadata, publish flow).',
                'later' => '—',
                'watch' => 'Update it when the website platform changes, or specs will send developers to the wrong place.',
            ],
            [
                'field' => 'outreach.follow_up_days',
                'enter' => 'Days, seeded **7** (1–60).',
                'now'   => 'Logging a pitch as sent on an outreach prospect sets its next follow-up this many days ahead.',
                'later' => 'When the date arrives, a follow-up task opens for the prospect’s owner in the Task queue.',
                'watch' => '—',
            ],
            [
                'field' => 'pages.crawl_delay_ms',
                'enter' => 'Milliseconds, seeded **1000**.',
                'now'   => 'The pause between page fetches during the site crawl for the Page Inventory.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'pages.exclude_patterns',
                'enter' => 'Paths to skip, one per line, e.g. **/checkout**. A path covers itself and anything below it (**/customer** matches /customer/login, not /customers). Start a line with ^ for a pattern.',
                'now'   => 'The site crawl skips matching sitemap addresses, and the Search Console load does not add matching pages to the Page Inventory.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'pages.site_url',
                'enter' => 'The public site root, seeded **https://www.nutraaxislabs.com**.',
                'now'   => 'The crawler reads robots.txt here to find the sitemaps and only crawls this host. The Search Console and GA4 loads use its host to match data to pages.',
                'later' => 'Named at the top of the developer packet from Audit & Issues.',
                'watch' => '—',
            ],
            [
                'field' => 'pages.type_rules',
                'enter' => 'One rule per line: type|pattern, e.g. **product|^/products/**. The first match wins; anything unmatched is **page**.',
                'now'   => 'Sets each page’s type in the Page Inventory when it is crawled or found in Search Console. Published Content Pipeline pages are always **content**.',
                'later' => 'The thin-content check only applies to **content**, **category** and **page** types.',
                'watch' => 'Patterns are regular expressions – a rule with a broken pattern is skipped.',
            ],
            [
                'field' => 'rank.drop_places',
                'enter' => 'Places, seeded **5**.',
                'now'   => 'The daily alerts check opens a rank_drop alert when a tracked keyword’s 7-day average position is this many places worse than the 7 days four weeks earlier. Leaving page 1 (10 or better to worse than 10) always alerts.',
                'later' => 'Also quoted on the Rank Tracker Movers tab.',
                'watch' => 'Only works while **rank_drop** is listed in alerts.rules.',
            ],
            [
                'field' => 'research.agent_max_results',
                'enter' => 'A number, seeded **8**.',
                'now'   => 'The most items the AI research agent may return per interest per run. Also sets how many web searches it may make (at least 3).',
                'later' => '—',
                'watch' => 'Higher numbers cost more per interest (more searches, longer replies).',
            ],
            [
                'field' => 'research.cluster_lookback_days',
                'enter' => 'Days, seeded **21**.',
                'now'   => 'Clustering considers scored items fetched within this many days.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'research.cluster_max_items',
                'enter' => 'A number, seeded **250**.',
                'now'   => 'The most scored items sent to one clustering run, most relevant first.',
                'later' => '—',
                'watch' => 'More items make each clustering call bigger and dearer.',
            ],
            [
                'field' => 'research.relevance_threshold',
                'enter' => 'A decimal from 0 to 1, seeded **0.6**.',
                'now'   => 'After scoring, an item whose best relevance (after interest weights) is below this is discarded; the rest go on to clustering.',
                'later' => 'Shown in the Topic Synthesis pipeline summary.',
                'watch' => 'Too low floods the Topic Board with noise; too high hides useful items. A blank box is read as 0 and keeps everything.',
            ],
            [
                'field' => 'research.score_batch_max_items',
                'enter' => 'A number, seeded **1000**.',
                'now'   => 'The most waiting items sent in one scoring batch.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'research.score_batch_min_items',
                'enter' => 'A number, seeded **25**.',
                'now'   => 'The hourly scoring job sends a batch once this many items are waiting, or once the oldest has waited 12 hours.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'research.score_text_chars',
                'enter' => 'Characters, seeded **1800**.',
                'now'   => 'How much of each item’s text (summary first, then body) is sent to the scoring AI.',
                'later' => '—',
                'watch' => 'More characters cost more per item.',
            ],
            [
                'field' => 'review.compliance_mode',
                'enter' => '**claims** or **all**.',
                'now'   => 'On submit, **claims** sends an asset or piece to compliance review only when its claims check found a health, product, ingredient, efficacy or condition statement or a flag term, or scored below 10. **all** sends everything.',
                'later' => 'Compliance tasks and the review queue follow from this.',
                'watch' => 'Anything other than **all** behaves as **claims**.',
            ],
            [
                'field' => 'seo.competitor_domains',
                'enter' => 'One competitor per line as **domain|name**, e.g. **thorne.com|Thorne**. Seeded with the seven brands in brand.competitors.',
                'now'   => 'Rank Tracker imports keep positions only for our domain and these domains (subdomains included), labelled with the name. Backlinks & Outreach reads Semrush Backlink Gap columns for these domains and refuses them as outreach prospects.',
                'later' => 'The Rank Tracker Competitors tab lists one row per name.',
                'watch' => 'A competitor missing here is ignored in imports. Only names, domains and positions are stored – never their pages or content. Keep it in step with brand.competitors, which the AI prompts use.',
            ],
            [
                'field' => 'semrush.monthly_unit_budget',
                'enter' => 'Semrush API units per month, seeded **20000**.',
                'now'   => 'Not used at the moment – no scheduled job calls Semrush yet.',
                'later' => '—',
                'watch' => 'Changing it has no effect for now.',
            ],
            [
                'field' => 'seo.meta_max',
                'enter' => 'Characters, seeded **160**.',
                'now'   => 'The site crawl flags meta descriptions longer than this.',
                'later' => 'Shown on the page detail in Page Inventory.',
                'watch' => '—',
            ],
            [
                'field' => 'seo.meta_min',
                'enter' => 'Characters, seeded **70**.',
                'now'   => 'The site crawl flags meta descriptions shorter than this.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'seo.thin_words',
                'enter' => 'Words, seeded **250**.',
                'now'   => 'The site crawl flags content, category and general pages with fewer words than this as thin.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'seo.title_max',
                'enter' => 'Characters, seeded **60**.',
                'now'   => 'The site crawl flags page titles longer than this.',
                'later' => 'Shown on the page detail in Page Inventory.',
                'watch' => '—',
            ],
            [
                'field' => 'seo.title_min',
                'enter' => 'Characters, seeded **30**.',
                'now'   => 'The site crawl flags page titles shorter than this.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'tasks.sla_days',
                'enter' => 'One line per task kind: kind|days, e.g. **compliance|2**. Kinds: brief, compliance, editorial, publish, schedule, reply.',
                'now'   => 'Sets the due date (Central) of automatic tasks – this many days after the event that opened the task.',
                'later' => 'Overdue tasks stand out on Tasks; the User Manual lists the current deadlines.',
                'watch' => 'A kind with no line gets 2 days. Site-issue triage tasks also get 2 days unless you add a **triage** line.',
            ],
            [
                'field' => 'taxonomy.product_lines',
                'enter' => 'Product lines, one per line. Blank as shipped.',
                'now'   => 'Fills the **Product line** list on interests. The chosen line is added to the interest’s description for the research agent.',
                'later' => '—',
                'watch' => 'Renaming or removing a line does not update interests that already use it.',
            ],
            [
                'field' => 'taxonomy.therapeutic_areas',
                'enter' => 'Therapeutic areas, one per line.',
                'now'   => 'Fills the area lists on interests, products and topics and the Claims filter. The scoring and clustering AI tag items and topics with these exact names.',
                'later' => 'Area tags on items and topics.',
                'watch' => 'Renaming or removing an area does not update records already tagged; a topic whose area is no longer listed loses it the next time the topic is saved.',
            ],
        ],
    ],
    'claim' => [
        'page'    => 'research-claims',
        'form'    => 'Claims → Add claim / Edit claim',
        'open'    => ['research-claims', ''],
        'who'     => 'Marketing admin (Create access for new, Update access to edit); approval needs full Marketing access',
        'purpose' => 'Adds or edits one piece of claim wording. Approved claims are the only product or ingredient benefit statements the AI may write and the claims check will accept. New claims, and approved claims whose wording or details change, are drafts until approved.',
        'note'    => '**Add claim** / **Save claim** saves the claim as a draft, or keeps it approved if only the source document or notes changed. **Approve** in the list is for full Marketing admins and only works if someone else edited the claim last. Only approved claims reach the AI: those linked to a topic on the Topic Board, plus – for Content Pipeline pieces – every approved claim of the piece’s product.',
        'fields'  => [
            [
                'field' => 'Product',
                'enter' => 'Pick the product, or **General (no product)** for wording not tied to one product.',
                'now'   => 'Given to the AI with the wording (“product | wording”). A product’s approved claims go automatically to every Content Pipeline piece for that product.',
                'later' => 'Campaigns only get claims linked to their topic, whatever the product.',
                'watch' => 'General claims reach the AI only when linked to a topic. Changing the product of an approved claim returns it to draft.',
            ],
            [
                'field' => 'Type',
                'enter' => '**Headline**, **Benefit claim** (default), **Mechanism**, **Ingredient** or **General / formula**.',
                'now'   => 'Orders the list (headlines first) and drives the Type filter.',
                'later' => 'Shown on topics that link the claim.',
                'watch' => 'Not given to the AI. Changing it on an approved claim returns it to draft.',
            ],
            [
                'field' => 'Claim wording', 'req' => true,
                'enter' => 'The exact approved wording, up to 1,000 characters, as it appears on the flyer.',
                'now'   => 'Given word for word (first 400 characters) to the AI that writes campaigns and content, and to the claims check, which accepts a statement only if it matches an approved claim’s wording or meaning without strengthening it.',
                'later' => 'Pieces that use it list it under **Claims used**.',
                'watch' => 'Any change sends an approved claim back to draft, and the AI can’t use it until it is approved again. Keep it under 400 characters so the AI sees all of it.',
            ],
            [
                'field' => 'Ingredient',
                'enter' => 'The ingredient the claim is about, up to 150 characters.',
                'now'   => 'Shown in the list and found by Search.',
                'later' => '—',
                'watch' => 'Not given to the AI. Changing it on an approved claim returns it to draft.',
            ],
            [
                'field' => 'Evidence tier',
                'enter' => '**Clinical (human studies)** (default), **Mechanistic**, **Traditional use** or **Label / formula fact**.',
                'now'   => 'Shown in the list and on topics that link the claim; drives the Evidence filter.',
                'later' => '—',
                'watch' => 'Not given to the AI or the claims check – it is for reviewers. Changing it on an approved claim returns it to draft.',
            ],
            [
                'field' => 'Flyer references',
                'enter' => 'The reference numbers from the product’s flyer, up to 100 characters, e.g. **1-3, 7-8**.',
                'now'   => 'Points to the numbered list in the product’s **Flyer references** (Products tab).',
                'later' => '—',
                'watch' => 'Not checked against the product’s list and not given to the AI. Changing it on an approved claim returns it to draft.',
            ],
            [
                'field' => 'Audience',
                'enter' => '**Both** (default), **Practitioner** or **Consumer**.',
                'now'   => 'Saved and shown in the list.',
                'later' => '—',
                'watch' => 'Not used to filter claims: a Consumer-only claim still reaches the AI for practitioner content, and the other way round – keep such claims off topics for the other audience. Changing it on an approved claim returns it to draft.',
            ],
            [
                'field' => 'Status',
                'enter' => 'New or draft claims: **Draft** or **Retired**. Approved claims: **Approved (edits return it to draft)** or **Retired**.',
                'now'   => 'Only approved claims are given to the AI and the claims check. Retired takes a claim out of use but keeps it.',
                'later' => 'Draft and retired claims stay linked to topics but are left out of generation.',
                'watch' => 'You can’t approve from this form – use **Approve** in the list.',
            ],
            [
                'field' => 'Source document',
                'enter' => 'Where the wording came from, up to 200 characters (e.g. the flyer name).',
                'now'   => 'Saved for reference; no job reads it at the moment.',
                'later' => '—',
                'watch' => 'Editing it keeps a claim approved.',
            ],
            [
                'field' => 'Requires DSHEA disclaimer',
                'enter' => 'Ticked by default.',
                'now'   => 'Marks the claim with ‡ for the AI. The compliance rules tell it to end any asset using a ‡ claim with the DSHEA disclaimer (not on X), and the claims check flags a missing disclaimer.',
                'later' => 'Shown as ‡ in the list and under **Claims used**.',
                'watch' => 'Untick only for statements that need no disclaimer, such as label or formula facts. Changing it on an approved claim returns it to draft.',
            ],
            [
                'field' => 'Notes',
                'enter' => 'Anything reviewers should know, up to 1,000 characters.',
                'now'   => 'Shown under the wording in the list and found by Search.',
                'later' => '—',
                'watch' => 'Not given to the AI. Editing notes keeps a claim approved.',
            ],
        ],
    ],
    'claim-product' => [
        'page'    => 'research-claims',
        'form'    => 'Products → Add product / Edit product',
        'open'    => ['research-claims', 'product.php'],
        'who'     => 'Marketing admin (Create access for new, Update access to edit)',
        'purpose' => 'The marketing record for one product. Claims hang off it, the Content Pipeline gives its details to the AI for pieces about it, and the scoring AI uses active products to tag harvested items.',
        'fields'  => [
            [
                'field' => 'Name', 'req' => true,
                'enter' => 'The product name, up to 100 characters.',
                'now'   => 'Names the product in the Claims list, the Content Pipeline product list and the claim lines given to the AI. Active products are given to the scoring AI by name so it can tag items that mention them.',
                'later' => 'Product tags on items and topics.',
                'watch' => 'Must be unique (“A product with that name already exists.”). Renaming does not re-tag items already scored.',
            ],
            [
                'field' => 'Therapeutic area',
                'enter' => 'Pick from the list (Admin & Jobs → Settings, taxonomy.therapeutic_areas), or —.',
                'now'   => 'Given to the scoring AI with the product. The Claims tab’s area filter uses the product’s area.',
                'later' => '—',
                'watch' => 'If the area is missing, ask an admin to add it in Settings.',
            ],
            [
                'field' => 'Headline',
                'enter' => 'The product’s one-line positioning, up to 300 characters.',
                'now'   => 'Shown under the product name and in the Products list. Given to the AI for briefs, drafts and revisions of pieces linked to this product.',
                'later' => '—',
                'watch' => 'The AI treats it as context, not an approved claim – keep it within approved wording.',
            ],
            [
                'field' => 'Summary',
                'enter' => 'A short description, up to 2,000 characters.',
                'now'   => 'Given to the Content Pipeline AI (first 600 characters) for pieces linked to this product.',
                'later' => '—',
                'watch' => 'Keep benefit language to approved claims.',
            ],
            [
                'field' => 'Formula (per serving)',
                'enter' => 'Ingredients and amounts per serving, up to 2,000 characters.',
                'now'   => 'Given to the Content Pipeline AI (first 600 characters). For active products, also given to the scoring AI (first 250 characters) so it can recognise items about the ingredients.',
                'later' => 'Product pages written in the Content Pipeline build on it.',
                'watch' => 'Put the key ingredients first – the scoring AI only sees the start.',
            ],
            [
                'field' => 'Suggested use',
                'enter' => 'Label directions, up to 1,000 characters.',
                'now'   => 'Given to the Content Pipeline AI (first 300 characters) for pieces linked to this product.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Intended use (one per line)',
                'enter' => 'Intended uses from the flyer, one per line, up to 2,000 characters.',
                'now'   => 'Shown on the product record.',
                'later' => '—',
                'watch' => 'Saved for reference; no job reads it at the moment.',
            ],
            [
                'field' => 'Flyer references (numbered, one per line)',
                'enter' => 'The flyer’s numbered reference list, one reference per line.',
                'now'   => 'Shown on the product record; claims point to these numbers in their **Flyer references**.',
                'later' => '—',
                'watch' => 'Not given to the AI. Keep the numbering stable – claims refer to it by number.',
            ],
            [
                'field' => 'Source document',
                'enter' => 'The flyer or document the record came from, up to 200 characters.',
                'now'   => 'Shown on the product record.',
                'later' => '—',
                'watch' => 'Saved for reference; no job reads it at the moment.',
            ],
            [
                'field' => 'Status',
                'enter' => '**Active** (default), **Paused** or **Retired**.',
                'now'   => 'Only active products are given to the scoring AI for tagging.',
                'later' => 'Paused and retired products still appear in the Content Pipeline product list, and their approved claims still reach the AI.',
                'watch' => 'When a product is withdrawn, retire its claims as well.',
            ],
            [
                'field' => 'Review notes',
                'enter' => 'Open questions or cautions, up to 2,000 characters.',
                'now'   => 'Shown as a red notice at the top of the product page and as ⚠ in the Products list.',
                'later' => '—',
                'watch' => 'Not given to the AI. Clear it once the question is settled.',
            ],
        ],
    ],
    'prompt-version' => [
        'page'    => 'research-prompt-lab',
        'form'    => 'Prompt → New version / Create prompt',
        'open'    => ['research-prompt-lab', ''],
        'who'     => 'Marketing admin (full Marketing access)',
        'purpose' => 'Every AI call in Marketing & Research uses the active version of a prompt. This form saves a new version, prefilled from the active one – it never changes an existing version, so you can compare and roll back.',
        'note'    => '**Save new version** adds the next version number. It goes live only if you tick **Activate this version immediately** (the first version of a new prompt is always live). **Activate** in the versions table switches the live version – use it to roll back. A change applies from the next AI call; scoring batches already sent finish with the version they were sent with.',
        'fields'  => [
            [
                'field' => 'Prompt key', 'req' => true,
                'enter' => 'Fixed for an existing prompt. For **New prompt**, a key like area.name: lowercase letters, numbers and underscores, with at least one dot.',
                'now'   => 'Jobs look prompts up by key: research.discover, research.score_item, research.cluster_topics, campaign.generate, campaign.claims_check, campaign.revise_asset, content.brief, content.draft, content.revise, engagement.response_triage, engagement.weekly_digest and seo.fix_spec.',
                'later' => '—',
                'watch' => 'A new key does nothing until a job is built to call it. A bad key gives “Prompt key must look like area.name…”.',
            ],
            [
                'field' => 'Provider',
                'enter' => '**Anthropic (Claude)** or **OpenAI**.',
                'now'   => 'Which AI company the call goes to.',
                'later' => 'Spend reports group calls by provider.',
                'watch' => 'research.score_item must stay Anthropic – scoring runs as a half-price Anthropic batch and the job refuses anything else.',
            ],
            [
                'field' => 'Model',
                'enter' => 'The exact model id, e.g. **claude-haiku-4-5**, or blank for the provider default (Admin & Jobs → Settings, ai.anthropic.model / ai.openai.model).',
                'now'   => 'Sent with each call.',
                'later' => 'Spend reports group calls by model; cost is estimated from ai.pricing.',
                'watch' => 'A wrong id makes every call fail. A model missing from ai.pricing is costed at $0 and escapes the monthly budget.',
            ],
            [
                'field' => 'Temperature',
                'enter' => 'A number from 0 to 1, in steps of 0.05; blank uses the provider’s default. The seeded claims check uses 0, the research agent 0.2.',
                'now'   => 'Sent with each call; lower is more consistent, higher more varied. Values outside 0–1 are clamped.',
                'later' => '—',
                'watch' => 'Some newer models reject it, so the call is retried without it; OpenAI GPT-5 models never receive it.',
            ],
            [
                'field' => 'Max output tokens',
                'enter' => 'The longest reply allowed, 100–32,000 (default 2,000). Values outside the range are clamped.',
                'now'   => 'Caps the length, and output cost, of each reply.',
                'later' => '—',
                'watch' => 'Too low cuts replies off part-way, so the job fails or keeps only part of the result. Long drafts need room.',
            ],
            [
                'field' => 'System prompt',
                'enter' => 'Standing instructions: role, rules and reply format. Optional. Placeholders such as {{brand_name}} are filled in on each call.',
                'now'   => 'Sent as the system instructions.',
                'later' => '—',
                'watch' => 'Keep the reply format the job expects (for most prompts a JSON object or list with set field names) – change it and the job can’t read the reply.',
            ],
            [
                'field' => 'User template', 'req' => true,
                'enter' => 'The message sent on each call, with placeholders such as {{interest_name}}, {{approved_claims}} or {{body}}. Start from the active version and change only what you need.',
                'now'   => 'Each placeholder is replaced with the job’s data. A placeholder the job doesn’t supply becomes blank, with no error.',
                'later' => '—',
                'watch' => 'Don’t rename or drop placeholders – the AI silently loses that input. Prompts go to the AI provider: never paste customer or patient details into them. Blank gives “The user template is required.”',
            ],
            [
                'field' => 'Change notes',
                'enter' => 'What changed and why, up to 1,000 characters. Starts blank each time.',
                'now'   => 'Shown in the Notes column of the versions table.',
                'later' => '—',
                'watch' => 'Write enough to judge a rollback later.',
            ],
            [
                'field' => 'Activate this version immediately',
                'enter' => 'Tick to make the new version live on save; leave unticked to save it for later.',
                'now'   => 'The active version is the one every call uses; the previous one stays in the table for rollback.',
                'later' => '—',
                'watch' => 'The first version of a new prompt is always activated, ticked or not.',
            ],
        ],
    ],
];
