<?php

declare(strict_types=1);

return [
    'campaign-new' => [
        'page'    => 'marketing-campaigns',
        'form'    => 'New campaign',
        'open'    => ['marketing-campaigns', '?tab=new'],
        'who'     => 'Marketing admin (Create access)',
        'purpose' => 'Starts a single post, a social series or an email sequence from an accepted topic. These fields are the instructions the AI writes every asset from. Format, audience, channels, parts and days between parts cannot be changed afterwards; name, call to action and extra brief can.',
        'note'    => '**Create and generate** saves the campaign and asks the AI to write every asset straight away (a minute or two, usually a few cents), then runs the claims check on each one. **Create only** saves it as a draft so you can press **Generate content** on the campaign page later.',
        'fields'  => [
            [
                'field' => 'Topic', 'req' => true,
                'enter' => 'Pick an accepted topic from the Topic Board. The list shows the 200 most recently accepted.',
                'now'   => 'The topic’s title, summary, why it matters, angle, things to avoid, evidence items (the ones marked as evidence, otherwise its most relevant, up to 8) and its linked approved claims all go to the AI. Its title also starts the campaign’s tracking code (UTM campaign).',
                'later' => 'The campaign’s engagement score rolls up to this topic and its interest, which feeds the weekly review and interest priority suggestions.',
                'watch' => 'A topic with no linked approved claims means the AI may make no product or ingredient benefit claims – link claims in the Claims Matrix first if you need them. If the topic is later moved off Accepted, generating fails until it is accepted again.',
            ],
            [
                'field' => 'Format',
                'enter' => '**Single post**, **Series** or **Email**. Defaults to Single post.',
                'now'   => 'Tells the AI what to write: one post per channel, a series with a narrative arc (part 1 frames the question, middle parts each cover one evidence point, the last sums up), or an email sequence with 3 subject-line options and preview text per email.',
                'later' => 'Sets how many parts the calendar lays out and how far apart.',
                'watch' => 'Cannot be changed later – create a new campaign instead. Email needs the email channel set up in Admin & Jobs → Settings.',
            ],
            [
                'field' => 'Audience',
                'enter' => '**Both**, **Practitioner** or **Consumer**. Blank uses the topic’s audience, or Both if the topic has none.',
                'now'   => 'Tells the AI who it is writing for – tone and technical depth – in generation, every AI revision and the claims check.',
                'later' => 'Shown on the campaign list.',
                'watch' => 'Cannot be changed later.',
            ],
            [
                'field' => 'Social channels', 'req' => 'For posts and series',
                'enter' => 'Tick one or more. LinkedIn and Facebook are ticked by default. The number in brackets is the channel’s character limit. The list, limits and writing guidance come from Admin & Jobs → Settings.',
                'now'   => 'The AI writes one asset per channel per part, following that channel’s guidance (for example, X: under 260 characters, no product benefit claims). Each asset is claims-checked and measured against the channel’s limit.',
                'later' => 'The channel becomes the link’s UTM source, so site visits are reported per channel. Each channel has its own default posting time on the calendar.',
                'watch' => 'Email campaigns ignore these boxes. Every extra channel multiplies the assets to review – 3 parts on 2 channels is 6 assets. Cannot be changed later.',
            ],
            [
                'field' => 'Parts',
                'enter' => 'A number, default 3. **Series**: 2–10. **Email**: 1–6. **Single post**: always 1.',
                'now'   => 'How many posts in the series or emails in the sequence the AI writes.',
                'later' => 'Each part gets its own review and its own calendar slot.',
                'watch' => 'Numbers outside the range are refused with “Series campaigns need 2–10 parts.” or “Email campaigns need 1–6 parts.” Ignored for a single post.',
            ],
            [
                'field' => 'Days between parts',
                'enter' => 'A number from 1 to 30, default 2.',
                'now'   => 'Given to the AI (“posted 2 days apart”) so each part builds on the last.',
                'later' => '**Lay out campaign** on the Publishing Calendar puts part N on the start date plus (N − 1) × this many days.',
                'watch' => 'Ignored when there is only one part. Cannot be changed later.',
            ],
            [
                'field' => 'Name',
                'enter' => 'Up to 200 characters. Blank uses the topic title plus the format, for example “Berberine and glucose — Series”.',
                'now'   => 'Names the campaign in Campaign Studio, the review queue and the calendar.',
                'later' => 'Shown in tasks, the calendar CSV export, the Response Inbox and the Monday digest’s campaign scores.',
                'watch' => 'Not sent to the AI, and it does not change the tracking code – rename freely later.',
            ],
            [
                'field' => 'Call-to-action URL', 'req' => true,
                'enter' => 'A full address starting with http:// or https://, up to 1,000 characters. Pre-filled with the default from Admin & Jobs → Settings (https://nutraaxislabs.com).',
                'now'   => 'Becomes each asset’s tracked link: the URL plus UTM tags for channel, social or email, the campaign and the asset number. The tracked link replaces [LINK] in the copy-ready text.',
                'later' => 'GA4 visits that arrive through the link are matched back to the asset and campaign overnight – shown as Site traffic on the asset and counted in its engagement score.',
                'watch' => 'Do not add your own utm_ tags; they are added for you. Only visits to the site GA4 measures (nutraaxislabs.com) are counted.',
            ],
            [
                'field' => 'Call-to-action text',
                'enter' => 'Up to 200 characters. Example: Read the practitioner summary.',
                'now'   => 'Given to the AI as the call to action to write towards. Blank tells it “Learn more”.',
                'later' => 'Saved on each asset the AI writes.',
                'watch' => 'The AI writes its own wording around it – check the body, not this field, for what readers will see.',
            ],
            [
                'field' => 'Extra brief',
                'enter' => 'Up to 2,000 characters: an event, an offer, a point to lead with.',
                'now'   => 'Passed to the AI as an additional brief. If the topic has no angle, this text is used as the angle.',
                'later' => 'Kept on the campaign; changes apply the next time content is generated.',
                'watch' => 'This text goes to the AI provider – no customer names, contact details or order information. It cannot override the compliance rules or add claims that are not approved.',
            ],
        ],
    ],
    'campaign-settings' => [
        'page'    => 'marketing-campaigns',
        'form'    => 'Campaign → Campaign settings',
        'open'    => ['marketing-campaigns', ''],
        'who'     => 'Writer or coordinator (Update access)',
        'purpose' => 'Changes the parts of a campaign that stay editable after it is created. Format, audience, channels and parts are fixed.',
        'note'    => '**Save** stores the changes; it does not rewrite or re-check any asset. **Archive campaign** moves it to the Archived tab and locks these settings; its assets are not changed and anything scheduled stays on the calendar. **Restore campaign** on an archived campaign brings it back. The buttons above the asset list – **Generate content** / **Regenerate all**, **Check claims** and **Submit N for review** – run the AI, the claims check and submission for the whole campaign.',
        'fields'  => [
            [
                'field' => 'Name', 'req' => true,
                'enter' => 'Up to 200 characters.',
                'now'   => 'Renames the campaign everywhere it is shown.',
                'later' => 'Tasks, the calendar, the CSV export and the Monday digest pick up the new name.',
                'watch' => 'The tracking code (UTM campaign) does not change, so traffic keeps matching.',
            ],
            [
                'field' => 'Call-to-action URL', 'req' => true,
                'enter' => 'A full address starting with http:// or https://, up to 1,000 characters.',
                'now'   => 'Changes the tracked link on every asset in the campaign straight away, including the copy-ready text and the calendar export for assets already scheduled.',
                'later' => 'Traffic from the new link is matched to the same campaign and assets.',
                'watch' => 'Posts already live keep the link they went out with. Tell the coordinator if scheduled posts are already loaded into GoHighLevel – they hold the old link.',
            ],
            [
                'field' => 'Call-to-action text',
                'enter' => 'Up to 200 characters. Clearing it means “Learn more” next time.',
                'now'   => 'Saved for the next generation.',
                'later' => 'Only used when content is generated or regenerated.',
                'watch' => 'Changing it does not update existing assets – edit their bodies, or regenerate while every asset is still a draft.',
            ],
            [
                'field' => 'Extra brief',
                'enter' => 'Up to 2,000 characters.',
                'now'   => 'Saved for the next generation.',
                'later' => 'Only used when content is generated or regenerated.',
                'watch' => '**Regenerate all** replaces every draft asset and is only offered while every asset is a draft or has changes requested. Goes to the AI provider – no customer names, contact details or order information.',
            ],
        ],
    ],
    'asset-edit' => [
        'page'    => 'marketing-campaigns',
        'form'    => 'Asset → Edit',
        'open'    => ['marketing-campaigns', ''],
        'who'     => 'Writer (Update access)',
        'purpose' => 'Hand-edits one asset. Every saved change makes a new version and re-runs the claims check, because the score must match the words that will be posted.',
        'note'    => '**Save and re-check** saves and, if anything changed, runs the claims check straight away. Editing an asset that is in review or approved sends it back to draft and clears both reviews. Scheduled assets must be taken off the calendar first; posted assets cannot be edited. **Archive asset** removes it from use – and while any asset is archived, **Regenerate all** is no longer offered for the campaign. **Run claims check** and **Submit for review** sit just above; submitting needs a current check at or above the minimum score and the [LINK] placeholder in the body.',
        'fields'  => [
            [
                'field' => 'Subject',
                'enter' => 'Email assets only. The subject line, up to 300 characters.',
                'now'   => 'Read by the claims check with the body. Names the asset in lists.',
                'later' => 'Shown in the copy-ready preview, the calendar’s **Copy text** and the CSV export for loading into GoHighLevel.',
                'watch' => 'The AI’s alternative subject lines (Variants) are not edited here and are not claims-checked – pick one and paste it here if you prefer it.',
            ],
            [
                'field' => 'Preview text',
                'enter' => 'Email assets only. The inbox preview line, up to 300 characters. The AI aims for under 90.',
                'now'   => 'Read by the claims check.',
                'later' => 'Included in the calendar’s **Copy text** and CSV export.',
                'watch' => '—',
            ],
            [
                'field' => 'Internal title',
                'enter' => 'Social assets only. A short name for the post, up to 300 characters.',
                'now'   => 'Names the asset in the campaign, review queue and calendar. Also read by the claims check.',
                'later' => 'Names the asset in the Monday digest’s top assets.',
                'watch' => 'Not part of the posted text.',
            ],
            [
                'field' => 'Body', 'req' => true,
                'enter' => 'The text to post or send. Put [LINK] exactly where the tracked link goes. The hint below the box shows the channel’s writing guidance.',
                'now'   => 'Claims-checked against the approved claims, the house rules and the flag terms, and measured against the channel’s character limit (on X, [LINK] counts as 23 characters).',
                'later' => 'Becomes the copy-ready text – with [LINK] swapped for the tracked link – that the coordinator loads into GoHighLevel.',
                'watch' => 'Without [LINK] the asset cannot be submitted. Cannot be empty.',
            ],
            [
                'field' => 'Hashtags',
                'enter' => 'Social assets only. Up to 500 characters, for example #berberine #metabolichealth. Follow the channel guidance on how many.',
                'now'   => 'Added after a blank line at the end of the copy-ready text, and counted towards the channel’s character limit.',
                'later' => '—',
                'watch' => 'The claims check does **not** read hashtags – keep health or disease words out of them, as reviewers only see them in the preview.',
            ],
            [
                'field' => 'Call-to-action text',
                'enter' => 'Up to 200 characters.',
                'now'   => 'Saved on the asset for reference.',
                'later' => '—',
                'watch' => 'Nothing else reads it – it is not in the copy-ready text. Changing it still counts as an edit: new version, re-check, and reviews cleared if the asset was in review or approved.',
            ],
            [
                'field' => 'Media notes',
                'enter' => 'Up to 1,000 characters: image or video direction for the designer.',
                'now'   => 'Shown as Media at the top of the asset.',
                'later' => '—',
                'watch' => 'Not posted and not claims-checked. Changing it still counts as an edit and clears reviews on an approved asset.',
            ],
        ],
    ],
    'asset-revise' => [
        'page'    => 'marketing-campaigns',
        'form'    => 'Asset → AI revise',
        'open'    => ['marketing-campaigns', ''],
        'who'     => 'Writer (Update access)',
        'purpose' => 'Asks the AI to rewrite one draft asset, either to fix its claims-check findings or to follow your instruction.',
        'note'    => '**Revise with AI** rewrites the asset (about a cent), saves it as a new version and re-runs the claims check. Only drafts and assets with changes requested can be revised.',
        'fields'  => [
            [
                'field' => 'Instruction',
                'enter' => 'Optional, up to 2,000 characters. Example: shorter, lead with the study finding, drop the children angle. Blank fixes every claims-check finding.',
                'now'   => 'Sent to the AI with the asset, its channel guidance, the approved claims and the current claims-check findings. The AI may rewrite the title, subject, preview text, body and hashtags; call-to-action text and media notes are kept.',
                'later' => 'Recorded in the review history as “AI revision: …”.',
                'watch' => 'A reviewer’s **Request changes** note is not passed on automatically – paste the part you want fixed. Revising makes you the last editor, so you cannot review this asset yourself. Goes to the AI provider – no customer names, contact details or order information.',
            ],
        ],
    ],
    'asset-review' => [
        'page'    => 'marketing-campaigns',
        'form'    => 'Asset → Compliance review / Editorial review',
        'open'    => ['marketing-campaigns', '?tab=review'],
        'who'     => 'Compliance reviewer (Marketing Compliance Review and Marketing Update access), then editor (full Marketing access)',
        'purpose' => 'Records a review decision. Compliance clears first when the claims check requires it; editorial approves after. Only an approved asset can be scheduled.',
        'note'    => '**Clear compliance** passes the asset to editorial. **Approve** makes it ready to schedule. **Request changes** sends it back to the author as Changes requested. You cannot review an asset you last edited or submitted.',
        'fields'  => [
            [
                'field' => 'Note', 'req' => 'For Request changes',
                'enter' => 'Up to 2,000 characters. Say exactly what must change and why, for example “‘supports healthy glucose’ is not our approved wording – use claim 12”.',
                'now'   => 'Saved in the asset’s review history with the version and claims score it applied to.',
                'later' => 'Request changes creates a high-priority task for the campaign’s creator to address the changes. Clearing compliance puts the asset in the editorial queue; final approval creates the coordinator’s task to schedule it.',
                'watch' => 'Required when requesting changes (“Say what needs to change.”). The note is not given to **Revise with AI** automatically – the writer must copy it into the instruction.',
            ],
        ],
    ],
    'asset-publishing' => [
        'page'    => 'marketing-campaigns',
        'form'    => 'Asset → Publishing',
        'open'    => ['marketing-calendar', ''],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Schedules an approved asset, records its GoHighLevel ID once loaded, and marks it posted once it is live. Nothing is sent to GoHighLevel from here – the coordinator loads each post by hand.',
        'note'    => '**Schedule** / **Reschedule** puts the asset on the calendar or moves it. **Save ID** records the GoHighLevel ID. **Mark posted** closes it out. **Take off the calendar** returns it to Approved and clears its GoHighLevel ID – needed before the content can be edited. **Update** corrects the link or ID after posting. **Lay out the whole campaign** opens the calendar’s Ready to schedule tab.',
        'fields'  => [
            [
                'field' => 'Schedule for (Central) / Move to (Central)', 'req' => true,
                'enter' => 'Date and time in Central time. Pre-filled with the current slot, or tomorrow at the channel’s default time.',
                'now'   => 'Puts the asset on the Publishing Calendar and in the review history. The calendar warns if it is within the minimum gap of another post on the same channel (20 hours by default) or before an earlier part of the series.',
                'later' => 'Until a GoHighLevel ID is saved, the coordinator gets a task to load it, due on the scheduled date. Once the time passes, it moves to Past due until marked posted.',
                'watch' => 'A time in the past is accepted – the notice reminds you to mark it posted once live. Moving an asset already in GoHighLevel does not move it there; the notice reminds you.',
            ],
            [
                'field' => 'Loaded into GoHighLevel as', 'req' => true,
                'enter' => 'The GoHighLevel Social Planner post ID or email campaign ID, up to 200 characters. Shown only while scheduled and not yet loaded.',
                'now'   => 'Marks the asset as loaded, removing it from the “Load into GoHighLevel” list and its task.',
                'later' => 'A post-metrics CSV import can match rows to the asset by this ID.',
                'watch' => 'Record it only after the post is actually created in GoHighLevel.',
            ],
            [
                'field' => 'Live at',
                'enter' => 'The public address of the live post, starting with http:// or https://, up to 1,000 characters. Leave blank for email.',
                'now'   => 'Saved as the live post link when you press **Mark posted**.',
                'later' => 'Shown as **Live post** on the asset, **View** on the calendar’s Posted tab and **View post** on Engagement & Performance, so people can open the original.',
                'watch' => 'Link to the post itself, not the tracked link or our site.',
            ],
            [
                'field' => 'Posted',
                'enter' => 'Date and time it went live, in Central time. Leave blank to use the scheduled time.',
                'now'   => 'Marks the asset Posted, clears it from Past due and closes the “confirm posted” task.',
                'later' => 'The nightly engagement score starts counting from this time; the score stays low-confidence for the first 7 days. The Monday digest shows it as the posted date.',
                'watch' => 'Cannot be more than a few minutes in the future. After posting, the asset can no longer be edited or taken off the calendar.',
            ],
            [
                'field' => 'Public post URL / GoHighLevel ID (after posting)',
                'enter' => 'Shown once the asset is posted, filled with what was recorded. Correct either and press **Update**.',
                'now'   => 'Replaces the stored live link and GoHighLevel ID.',
                'later' => 'Same uses as above.',
                'watch' => 'Clearing a box removes the value.',
            ],
        ],
    ],
    'calendar-schedule' => [
        'page'    => 'marketing-calendar',
        'form'    => 'Ready to schedule → Lay out campaign / Schedule',
        'open'    => ['marketing-calendar', '?tab=ready'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Puts approved assets on the calendar – a whole campaign at once, or one asset at a time.',
        'note'    => '**Lay out campaign** schedules every approved, unscheduled asset of that campaign; parts still in drafting or review are left off and counted in the notice. **Schedule** on a row schedules just that asset.',
        'fields'  => [
            [
                'field' => 'Start', 'req' => true,
                'enter' => 'The date part 1 goes out. Defaults to tomorrow.',
                'now'   => 'Part N is scheduled on this date plus (N − 1) × the campaign’s days between parts.',
                'later' => 'Scheduled assets appear on the Month and Upcoming tabs and in the coordinator’s load tasks.',
                'watch' => 'A past date is accepted without warning – check the date before pressing the button.',
            ],
            [
                'field' => 'Time',
                'enter' => 'Optional, 24-hour time in Central time (HH:MM). Blank uses each channel’s default time (Admin & Jobs → Settings); channels with no default use 09:00.',
                'now'   => 'Sets the time of day for every asset laid out.',
                'later' => '—',
                'watch' => 'One time for all channels can put several posts at the same moment; blank is usually better.',
            ],
            [
                'field' => 'Schedule (Central)', 'req' => true,
                'enter' => 'Date and time for one asset in Central time. Pre-filled with tomorrow plus the part’s spacing, at the channel’s default time.',
                'now'   => 'Schedules that asset only.',
                'later' => 'Same as the asset page’s **Schedule for**.',
                'watch' => 'The calendar warns about posts on the same channel closer than the minimum gap, or series parts out of order – check the ⚠ marks after scheduling.',
            ],
        ],
    ],
    'calendar-todo' => [
        'page'    => 'marketing-calendar',
        'form'    => 'Coordinator to-do → Save GoHighLevel ID / Mark posted',
        'open'    => ['marketing-calendar', '?tab=todo'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'The coordinator’s two daily jobs: record the GoHighLevel ID once each scheduled asset is loaded, and confirm posts went live once their time has passed.',
        'note'    => '**Save** records the ID (the Upcoming tab has the same box). **Posted** marks the asset posted at its scheduled time – to record a different time, use **Mark posted** on the asset page. The **CSV** export at the top gives the copy-ready text and tracked links for loading. Nothing is sent to GoHighLevel from here.',
        'fields'  => [
            [
                'field' => 'GoHighLevel ID', 'req' => true,
                'enter' => 'In the Load into GoHighLevel list: the Social Planner post ID or email campaign ID, up to 200 characters.',
                'now'   => 'Marks the asset as loaded and removes it from the list and from the coordinator’s load task.',
                'later' => 'A post-metrics CSV import can match rows to the asset by this ID.',
                'watch' => 'Taking the asset off the calendar later clears the ID, and the notice reminds you to delete it in GoHighLevel.',
            ],
            [
                'field' => 'Public post URL',
                'enter' => 'In the Past due list: the address of the live post, starting with http:// or https://. Leave blank for email.',
                'now'   => 'Saved as the live post link; the asset becomes Posted and leaves the Past due list and task.',
                'later' => 'Shown on the Posted tab, the asset and Engagement & Performance. The nightly engagement score starts counting from the posted time.',
                'watch' => 'Only confirm once you have seen the post live. If it didn’t go out, open the asset and reschedule it instead.',
            ],
            [
                'field' => 'GoHighLevel ID (in Past due)',
                'enter' => 'Shown only if no ID was recorded. Optional, up to 200 characters.',
                'now'   => 'Saved with the posted record.',
                'later' => 'Same as above.',
                'watch' => '—',
            ],
        ],
    ],
];
