<?php

declare(strict_types=1);

return [
    'content-new' => [
        'page'    => 'marketing-content',
        'form'    => 'New piece',
        'open'    => ['marketing-content', '?tab=new'],
        'who'     => 'Marketing admin (Create access)',
        'purpose' => 'Starts a long-form page or blog post. These fields are the instructions the AI brief is written from. Type, topic, product, keywords, audience and length lock once the brief is approved; title, owner, due date, planned URL and notes can change any time.',
        'note'    => '**Create and write the brief** saves the piece and asks the AI for a brief straight away (under a minute, usually a few cents). **Create only** saves it as an idea so you can write the brief later.',
        'fields'  => [
            [
                'field' => 'Working title',
                'enter' => 'A name for the piece, up to 300 characters. Leave blank to use the topic’s title.',
                'now'   => 'Names the piece on the board, in tasks and in the review queue.',
                'later' => 'The published title comes from the approved version the AI or writer produces, not from this field.',
                'watch' => 'Required if no topic is linked.',
            ],
            [
                'field' => 'Type', 'req' => true,
                'enter' => 'Pick the kind of page, for example Article (~1,200 words) or Blog post (~900 words). The list is set in Admin & Jobs → Settings (content.types).',
                'now'   => 'Sets the default length and the writing guidance given to the AI for the brief and draft.',
                'later' => 'Choose **Blog post** for posts meant for nutraaxislabs.com/our-blog — though any approved piece can be published there.',
                'watch' => 'Locks when the brief is approved.',
            ],
            [
                'field' => 'Audience',
                'enter' => '**Practitioner**, **Consumer** or **Both**. Blank uses the topic’s audience, or Both if there is no topic.',
                'now'   => 'Tells the AI who it is writing for — tone and technical depth — in the brief, the draft and every AI revision.',
                'later' => '—',
                'watch' => 'Locks when the brief is approved.',
            ],
            [
                'field' => 'Topic',
                'enter' => 'Pick an accepted topic from the Topic Board, or None.',
                'now'   => 'The topic’s summary, why it matters, angle, things to avoid, marked evidence and linked approved claims all go into the brief and draft.',
                'later' => 'The piece’s engagement score rolls up to this topic and its interest, which feeds the weekly review.',
                'watch' => 'You must link a topic **or** a product. Only accepted topics are listed — accept it on the Topic Board first.',
            ],
            [
                'field' => 'Product',
                'enter' => 'Pick a product, or None. The list shows how many approved claims each has.',
                'now'   => 'All of the product’s approved claims become usable in the copy, and its details go to the AI.',
                'later' => 'The claims check on every version measures the text against these claims.',
                'watch' => 'Required for a Product page. A product with no approved claims gives the AI nothing to say about it — add claims in the Claims Matrix first.',
            ],
            [
                'field' => 'Keyword list',
                'enter' => 'Pick the Keyword Universe keyword this piece targets, or None.',
                'now'   => 'Records the target keyword and fills Primary keyword if you leave that blank.',
                'later' => 'Ties the piece to keyword research, so you can check whether a page already targets the same keyword.',
                'watch' => 'Locks when the brief is approved.',
            ],
            [
                'field' => 'Primary keyword',
                'enter' => 'The main search phrase, up to 200 characters. Example: berberine for blood sugar. Blank uses the keyword list choice.',
                'now'   => 'The AI builds the title, headings, meta title and meta description around it. With none, the AI picks the natural search phrase.',
                'later' => 'After publishing, compare it with the page’s Search Console queries on Page Inventory.',
                'watch' => 'One phrase only — put the rest in Secondary keywords.',
            ],
            [
                'field' => 'Secondary keywords',
                'enter' => 'Related phrases, comma separated, up to 1,000 characters.',
                'now'   => 'The AI works them into the brief and draft where they fit naturally.',
                'later' => '—',
                'watch' => 'A handful is plenty; long lists lead to stuffed copy.',
            ],
            [
                'field' => 'Target words',
                'enter' => 'A number from 200 to 5,000, or blank for the type’s default.',
                'now'   => 'The length the brief plans for and the draft aims at.',
                'later' => '—',
                'watch' => 'Locks when the brief is approved.',
            ],
            [
                'field' => 'Due',
                'enter' => 'The date the piece should be finished.',
                'now'   => 'Used as the due date on the piece’s brief and drafting tasks instead of the standard deadlines.',
                'later' => 'Overdue tasks show in Tasks and are counted in the Monday digest.',
                'watch' => '—',
            ],
            [
                'field' => 'Owner',
                'enter' => 'The person responsible. Defaults to you.',
                'now'   => 'Gets the brief-review and drafting tasks for this piece.',
                'later' => 'Shown on the board and list so blocked pieces have a name against them.',
                'watch' => '—',
            ],
            [
                'field' => 'Planned URL',
                'enter' => 'Optional full address starting with https://, for example the site’s /learn/… path.',
                'now'   => 'Shown on the piece and in the search-result preview, and pre-filled when you mark it published.',
                'later' => '—',
                'watch' => 'For blog posts the address is set when you press Publish to blog, not here.',
            ],
            [
                'field' => 'Notes for the brief',
                'enter' => 'Up to 2,000 characters: a point to lead with, a question practitioners keep asking, pages to link to.',
                'now'   => 'Passed to the AI as extra instructions when it writes the brief.',
                'later' => 'Kept on the piece for the writer and reviewers.',
                'watch' => 'This text goes to the AI provider — no customer names, contact details or order information.',
            ],
        ],
    ],

    'content-brief' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Brief',
        'open'    => ['marketing-content', '?tab=board'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'The plan the draft is written from: search intent, reader, angle, outline, evidence to cite, approved claims, FAQs, call to action and suggested meta. Edit it until it is right, then approve it to move the piece to drafting.',
        'note'    => '**Write the brief with AI** (or **Regenerate with AI**) asks the AI for a brief from the topic’s evidence, the keywords, the product, the approved claims and the piece’s notes — under a minute, a few cents — and replaces whatever is in the box. **Save brief** saves your edits. **Approve brief** appears once a brief is saved: it locks the brief and the targeting fields in Details and moves the piece to Draft. At the draft stage, **Reopen the brief** unlocks it again; existing versions are kept.',
        'fields'  => [
            [
                'field' => 'Brief (Markdown)', 'req' => true,
                'enter' => 'The brief in Markdown: ## section headings, ### outline headings and - bullet points. Write it yourself or edit the AI’s. Up to 30,000 characters are kept.',
                'now'   => 'Saving moves the piece to the Brief stage, records who wrote it and when, and adds a line to the review history. The owner gets an **Approve the brief** task.',
                'later' => 'Once approved, this text — including your edits — is exactly what the AI drafts from. Every **New AI draft from the brief** starts from it again.',
                'watch' => '**Approve brief** uses the saved brief: unsaved edits in the box are thrown away, so press **Save brief** first. Regenerating replaces your edits. If the linked topic is no longer accepted, the AI brief and AI draft stop with an error until you accept it again or unlink it.',
            ],
        ],
    ],

    'content-revise' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Draft (AI revise)',
        'open'    => ['marketing-content', '?tab=board'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Asks the AI to rewrite the current version at the draft stage — to fix claims-check findings, act on a reviewer’s note or make the change you describe.',
        'note'    => 'The other Draft buttons: **Write the draft with AI** / **New AI draft from the brief** writes a fresh version from the approved brief and claims-checks it (earlier versions are kept). **Run claims check** appears if the current version has not been checked. **Submit version N for review** needs a claims score at or above the minimum (Admin & Jobs → Settings, claims.min_score, default 7); it goes to compliance review if the check found claims, efficacy or health-condition references or flag terms (or if every piece must be reviewed), otherwise straight to editorial review.',
        'fields'  => [
            [
                'field' => 'AI revise',
                'enter' => 'Optional instruction, up to 2,000 characters. Example: Tighten the intro and add a section on dosing evidence. Leave blank to fix every claims-check finding and the latest reviewer note.',
                'now'   => 'Sent to the AI with the current version’s title, meta title, meta description and body, its claims-check findings (unapproved or disease statements, issues, flag terms), the latest **Request changes** note and the approved claims. The reply is saved as a new version (source **AI revision**) and claims-checked straight away.',
                'later' => 'The instruction is kept as the version’s note in the Versions table and in the review history.',
                'watch' => 'The AI rewrites the whole piece, so compare it with the previous version (**vs vN** in Versions). If the reply is cut off, no version is saved — try again. This text goes to the AI provider — no customer names, contact details or order information.',
            ],
        ],
    ],

    'content-review' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Compliance review / Editorial review',
        'open'    => ['marketing-content', '?tab=review'],
        'who'     => 'Compliance reviewer for the compliance step; Marketing admin (full Marketing access) for the editorial step. Not the person who wrote or submitted the version.',
        'purpose' => 'Records the reviewer’s decision on the submitted version. Compliance checks every statement against the approved claims; editorial checks accuracy, voice, structure, search intent and the call to action.',
        'note'    => '**Clear compliance** moves the piece to editorial review. **Approve** (editorial) makes it Approved and gives the owner a publish task. **Request changes** sends it back to Draft with a high-priority **Address review changes** task for the owner.',
        'fields'  => [
            [
                'field' => 'Note', 'req' => 'Required for Request changes',
                'enter' => 'Up to 2,000 characters. When requesting changes, say exactly what must change and where. Optional when clearing or approving.',
                'now'   => 'Saved in the review history with your decision, your name and the version number.',
                'later' => 'The latest **Request changes** note is given to the AI when the writer uses **Revise with AI**, so a blank revise works through it.',
                'watch' => 'Without a note, **Request changes** fails with “Say what needs to change.” If the piece was edited after it was submitted, it must be resubmitted before anyone can review it. The note goes to the AI provider on the next AI revision — no customer names, contact details or order information.',
            ],
        ],
    ],

    'content-blog-publish' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Publish to the blog',
        'open'    => ['marketing-content', '?tab=board'],
        'who'     => 'Marketing admin (full Marketing access)',
        'purpose' => 'Puts the approved current version on nutraaxislabs.com/our-blog the moment you click. The same form updates a live post with a newly approved version, or puts an unpublished post back.',
        'note'    => '**Publish to blog** / **Update blog post** copies the approved version’s title, meta title, meta description and body to the blog (headings step down one level, because the post title is the page heading). The piece becomes **Published** with the live link recorded. Later edits do not reach the blog until they are approved again and you press **Update blog post**.',
        'fields'  => [
            [
                'field' => 'Post address', 'req' => true,
                'enter' => '3–160 characters: lowercase letters, numbers and single hyphens, for example glp1-nutrient-gaps. Pre-filled from the title (cut to about 80 characters, with -2, -3 … added if another post has it), or with the current address for a post already published.',
                'now'   => 'Makes the live link: the blog page address + ?post= + this address. That link is saved as the piece’s live URL.',
                'later' => 'This is the link people share and the one opened from the posting history.',
                'watch' => 'Must not be used by another blog post. Changing it after publishing breaks links already shared.',
            ],
            [
                'field' => 'History summary',
                'enter' => 'One or two plain sentences, up to 300 characters. Pre-filled with the meta description, or the opening paragraph if there is none. Leave blank to use that default.',
                'now'   => 'Saved with the post; line breaks become spaces.',
                'later' => 'Shown under the title and date in the blog’s posting history. Also used as the post page’s description tag if the version has no meta description.',
                'watch' => 'A re-publish is pre-filled with the old summary — update it if the piece changed. It is public text, so keep it within the approved claims.',
            ],
            [
                'field' => 'Byline',
                'enter' => 'Author name, up to 150 characters. Defaults to the post’s current byline, else the blog.author setting in Admin & Jobs → Settings (NutraAxis Team). Blank uses the setting.',
                'now'   => 'Saved with the post.',
                'later' => 'Shown as “By …” under the post title on the blog.',
                'watch' => 'Use a person’s name only with their agreement.',
            ],
            [
                'field' => 'Header image URL',
                'enter' => 'Optional full image address starting with https://, up to 1,000 characters.',
                'now'   => 'Saved with the post. Blank means no image.',
                'later' => 'Shown at the top of the post on the blog.',
                'watch' => 'Must start with https:// or you get “The header image must be an https:// URL.” The image must be publicly reachable and one we have rights to use.',
            ],
            [
                'field' => 'Image description',
                'enter' => 'What the image shows, up to 300 characters. Blank uses the post title.',
                'now'   => 'Saved only when there is a header image.',
                'later' => 'The image’s alternative text, read by screen readers and shown if the image fails to load.',
                'watch' => 'Describe the image, not the article.',
            ],
        ],
    ],

    'content-live-url' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Mark published / Update URL',
        'open'    => ['marketing-content', '?tab=list'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'For pieces published somewhere other than the blog: after you put the approved version live yourself (copy the HTML or Markdown from the preview), record where it lives. **Update URL** corrects the address later.',
        'note'    => '**Mark published** is on approved pieces and moves them to **Published**. **Update URL** is on published and monitoring pieces. Both run the live check straight away. **Move to monitoring** (button, no fields) moves a published piece on once it is indexed. Neither form appears while the piece is live on the blog.',
        'fields'  => [
            [
                'field' => 'Live URL', 'req' => true,
                'enter' => 'The full page address starting with http:// or https://, up to 1,000 characters. Pre-filled with the live or planned URL.',
                'now'   => 'Saved as the piece’s live URL and logged in the review history. If it is a page on our own site, it is added to Page Inventory as a content page with the piece’s primary and secondary keywords, then crawled; the result (live, failed, title mismatch, page issues) is written to the review history.',
                'later' => 'The page’s search and analytics traffic counts towards the piece’s engagement score, which rolls up to its topic and interest. A failed live check is retried every morning until it passes.',
                'watch' => 'Put the page live first — nothing is published by this form. Pages on other sites are saved but not checked or added to Page Inventory.',
            ],
        ],
    ],

    'content-blog-unpublish' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Blog post → Unpublish',
        'open'    => ['marketing-content', '?tab=list'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Takes the post off the public blog straight away. A published or monitoring piece goes back to **Approved** so it can be put back on the blog or published elsewhere; a piece already back in draft stays there.',
        'note'    => '**Unpublish from blog** asks for confirmation. **Move to monitoring** (button, no fields) moves a published blog piece on; blog traffic shows on the /our-blog page in Page Inventory, not per post.',
        'fields'  => [
            [
                'field' => 'Reason',
                'enter' => 'Optional, up to 2,000 characters. Example: Claim withdrawn pending new evidence.',
                'now'   => 'Saved in the review history. The piece’s live URL is cleared.',
                'later' => 'The post keeps its address, summary, byline and image, which are pre-filled when you put it back.',
                'watch' => 'Links already shared stop working until the post is published again.',
            ],
        ],
    ],

    'content-version' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Edit (save a new version)',
        'open'    => ['marketing-content', '?tab=list'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Write the draft yourself or edit the current version. Every save is a new version; earlier versions are kept and can be compared.',
        'note'    => '**Save as new version and re-check** saves the version and re-runs the claims check (AI, a few cents). If nothing changed you see “No changes.” Saving a piece that is in review, approved, published or monitoring sends it back to Draft and clears its reviews; a published piece keeps its live URL.',
        'fields'  => [
            [
                'field' => 'Page title', 'req' => true,
                'enter' => 'The headline, up to 300 characters.',
                'now'   => 'Saved on the new version and sent to the claims check.',
                'later' => 'The page’s main heading and the blog post title (also listed in the blog’s posting history). For pages published outside the blog, the live check warns if the live page’s title does not match it.',
                'watch' => '—',
            ],
            [
                'field' => 'Meta title',
                'enter' => 'The title shown in search results, up to 60 characters (the box allows 200). Count shown under the search-result preview.',
                'now'   => 'Sent to the claims check, which lists it as an issue if it is missing or over 60 characters.',
                'later' => 'The browser-tab title of the blog post (“… | NutraAxis Blog”); the page title is used if blank.',
                'watch' => 'The claims check only reports the length — it does not stop you submitting.',
            ],
            [
                'field' => 'Meta description',
                'enter' => 'The summary shown in search results, up to 155 characters (the box allows 400).',
                'now'   => 'Sent to the claims check, which lists it as an issue if it is missing or over 155 characters.',
                'later' => 'The blog post page’s description tag and the default blog history summary.',
                'watch' => 'It is public copy, so it must stay within the approved claims like the body.',
            ],
            [
                'field' => 'Body (Markdown)', 'req' => true,
                'enter' => 'The article in Markdown: ## / ### headings, - lists, **bold**, *italic* and [text](https://…) links. No # heading — the page title is the only H1.',
                'now'   => 'Word count is worked out and the claims check reviews every statement against the approved claims. It also flags a # heading, any links (confirm they are real) and fewer than 60% of the target words.',
                'later' => 'Exactly what the preview, the Copy HTML / Copy Markdown buttons and the blog show. On the blog, headings step down one level and reading time comes from the word count.',
                'watch' => 'Only the Markdown listed above is formatted; anything else shows as plain text. Links open in a new tab. Check the preview before saving.',
            ],
            [
                'field' => 'Change note',
                'enter' => 'Optional, up to 500 characters: what changed and why.',
                'now'   => 'Saved on the version and shown under its source in the Versions table.',
                'later' => '—',
                'watch' => 'A note alone does not make a new version — change the title, meta or body. Reviewers see it; the AI does not.',
            ],
        ],
    ],

    'content-details' => [
        'page'    => 'marketing-content',
        'form'    => 'Piece → Details',
        'open'    => ['marketing-content', '?tab=list'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Changes the piece’s setup after it is created. Type, audience, topic, product, keywords and length only show until the brief is approved; title, owner, due date, planned URL and notes can change any time.',
        'note'    => '**Save details** saves the form. **Archive** takes the piece off the board and closes its open tasks; it is not offered once the piece is published, and a piece live on the blog must be unpublished first.',
        'fields'  => [
            [
                'field' => 'Working title', 'req' => true,
                'enter' => 'Up to 300 characters.',
                'now'   => 'Renames the piece on the board, in its tasks and in the review queue.',
                'later' => 'Used as the topic title in the AI brief only when no topic is linked. The published title comes from the version, not this field.',
                'watch' => 'Cannot be blank.',
            ],
            [
                'field' => 'Type',
                'enter' => 'Pick the kind of page. The list is set in Admin & Jobs → Settings (content.types).',
                'now'   => 'Sets the default length and the writing guidance given to the AI.',
                'later' => '—',
                'watch' => 'Shown only until the brief is approved. A Product page must have a product. Changing the type does not rewrite an existing brief — press **Regenerate with AI**.',
            ],
            [
                'field' => 'Audience',
                'enter' => '**Practitioner**, **Consumer** or **Both**.',
                'now'   => 'Tells the AI who it is writing for in the brief, the draft and every AI revision.',
                'later' => '—',
                'watch' => 'Shown only until the brief is approved.',
            ],
            [
                'field' => 'Topic',
                'enter' => 'Pick an accepted topic, or None. The current topic stays in the list even if it is no longer accepted.',
                'now'   => 'The topic’s summary, angle, things to avoid, evidence and approved claims feed the AI brief and draft.',
                'later' => 'The piece’s engagement score rolls up to this topic and its interest.',
                'watch' => 'You must keep a topic **or** a product. If the topic is no longer accepted, AI brief and draft stop with an error.',
            ],
            [
                'field' => 'Product',
                'enter' => 'Pick a product, or None.',
                'now'   => 'The product’s approved claims become usable in the copy, and its details go to the AI.',
                'later' => 'The claims check on every version measures the text against these claims.',
                'watch' => 'Required for a Product page. Shown only until the brief is approved.',
            ],
            [
                'field' => 'Keyword list',
                'enter' => 'Pick the Keyword Universe keyword this piece targets, or None.',
                'now'   => 'Records the target keyword and fills Primary keyword if that is blank.',
                'later' => '—',
                'watch' => 'Shown only until the brief is approved.',
            ],
            [
                'field' => 'Primary keyword',
                'enter' => 'The main search phrase, up to 200 characters.',
                'now'   => 'The AI builds the title, headings and meta around it in the brief.',
                'later' => 'When the piece is published at a page on our site, it is added to that page’s keywords in Page Inventory.',
                'watch' => 'Shown only until the brief is approved. Changing it does not rewrite an existing brief.',
            ],
            [
                'field' => 'Secondary keywords',
                'enter' => 'Related phrases, comma separated, up to 1,000 characters.',
                'now'   => 'The AI works them into the brief where they fit.',
                'later' => 'Added to the published page’s keywords in Page Inventory (pages on our site only).',
                'watch' => 'Shown only until the brief is approved.',
            ],
            [
                'field' => 'Target words',
                'enter' => 'A number from 200 to 5,000, or blank for the type’s default.',
                'now'   => 'The length the brief plans for and the draft aims at.',
                'later' => 'The claims check flags a version under 60% of this length.',
                'watch' => 'Shown only until the brief is approved.',
            ],
            [
                'field' => 'Owner',
                'enter' => 'Anyone whose role can read Marketing, or Unassigned.',
                'now'   => 'Gets the piece’s brief, drafting and publish tasks. Unassigned sends them to the person who created the piece.',
                'later' => 'Shown on the board and list.',
                'watch' => '—',
            ],
            [
                'field' => 'Due',
                'enter' => 'The date the piece should be finished. Clear it to go back to the standard deadlines.',
                'now'   => 'Used as the due date on the piece’s write-the-brief, drafting and publish tasks.',
                'later' => 'Overdue tasks show in Tasks and are counted in the Monday digest.',
                'watch' => 'Brief-approval and review tasks keep their standard deadlines.',
            ],
            [
                'field' => 'Planned URL',
                'enter' => 'Optional full address starting with http:// or https://, up to 1,000 characters.',
                'now'   => 'Shown on the piece and in the search-result preview until it is published.',
                'later' => 'Pre-fills **Live URL** when you mark the piece published.',
                'watch' => 'Anything else fails with “The target URL must be a full http(s) address.” Blog posts get their address from **Publish to blog**.',
            ],
            [
                'field' => 'Notes',
                'enter' => 'Up to 2,000 characters: points to lead with, questions practitioners ask, pages to link to.',
                'now'   => 'Shown on the piece.',
                'later' => 'Passed to the AI the next time the brief is written or regenerated. The draft and revisions do not read them.',
                'watch' => 'Editing notes after the brief is approved does not change anything the AI writes. This text goes to the AI provider — no customer names, contact details or order information.',
            ],
        ],
    ],
];
