<?php

declare(strict_types=1);

return [
    'response-add' => [
        'page'    => 'marketing-performance',
        'form'    => 'Response Inbox → Add a response',
        'open'    => ['marketing-performance', 'inbox.php?tab=add'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Logs a comment, reply, DM, email reply or review on one of our posts so it is triaged, answered and counted. GoHighLevel is not connected yet, so responses are added by hand.',
        'note'    => '**Save and triage** saves the response and runs AI triage straight away. Claims risk and possible adverse events go to compliance with a 24-hour clock that starts at that moment.',
        'fields'  => [
            [
                'field' => 'In response to',
                'enter' => 'Pick the scheduled or posted asset it came in on, or leave “not linked to a post”.',
                'now'   => 'Links the response to the asset and its campaign, and gives the triage AI the post’s text as context.',
                'later' => 'Response counts (total, positive and risky) are added to the asset’s engagement score, which rolls up to its campaign, topic and interest.',
                'watch' => 'Link it whenever you know the post — unlinked responses don’t count towards any campaign.',
            ],
            [
                'field' => 'Channel', 'req' => true,
                'enter' => 'Where it was posted. Social channels come from Admin & Jobs → Settings.',
                'now'   => 'Sent to the triage AI and shown in the inbox.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Kind', 'req' => true,
                'enter' => '**Comment**, **Reply to a comment**, **Direct message**, **Email reply**, **Mention / tag**, **Review** or **Other**.',
                'now'   => 'Sent to the triage AI — a private message is read differently from a public comment.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Received (Central)',
                'enter' => 'When it arrived, in Central time. Defaults to now; it cannot be in the future.',
                'now'   => 'Orders the inbox, oldest first.',
                'later' => 'The Monday digest counts responses and escalations received that week by this time.',
                'watch' => 'The compliance clock starts when the response is saved and triaged, not at this time — log responses promptly.',
            ],
            [
                'field' => 'Link to it',
                'enter' => 'Optional full address (https://…) of the comment or thread.',
                'now'   => 'Lets whoever replies, and compliance, open the original in context.',
                'later' => '—',
                'watch' => 'Link to the thread rather than pasting the whole conversation into Text.',
            ],
            [
                'field' => 'Text', 'req' => true,
                'enter' => 'Paste only what they wrote, up to 4,000 characters.',
                'now'   => 'Emails, phone numbers and @handles are replaced with [email], [phone] and [handle] before it is saved. The cleaned text goes to the triage AI and to keyword rules for conditions, drugs and reactions, which decide the label and whether it goes to compliance.',
                'later' => 'Kept as the record compliance decides on and the reply is written from.',
                'watch' => 'Names are **not** removed automatically — leave out the person’s name, order numbers and any health details beyond what they posted.',
            ],
        ],
    ],
    'response-compliance' => [
        'page'    => 'marketing-performance',
        'form'    => 'Response → Record decision',
        'open'    => ['marketing-performance', 'inbox.php?tab=escalated'],
        'who'     => 'Compliance reviewer (Marketing Compliance Review and Update access)',
        'purpose' => 'Clears a response that was flagged as a claims risk or a possible adverse event. Nobody replies until this is recorded, and it is the only record of what may be said and whether an adverse event was reported.',
        'note'    => '**Record decision** closes the compliance task for this response and stops its deadline clock. The form only shows while the response is **With compliance**.',
        'fields'  => [
            [
                'field' => 'Decision', 'req' => true,
                'enter' => '**Cleared to reply (guidance below)** or **No public reply — close it**.',
                'now'   => 'Cleared to reply moves the response back to Open, where the coordinator’s “Reply to … responses” task picks it up. No public reply closes it straight away.',
                'later' => 'The escalation stops counting as open or overdue on Engagement & Performance and in the Monday digest.',
                'watch' => 'To send a response back to compliance later, reopen it and set a **Claims risk** or **Possible adverse event** label again — reviewers are not emailed a second time, but the task opens.',
            ],
            [
                'field' => 'Decision and guidance', 'req' => true,
                'enter' => 'Up to 2,000 characters. If cleared: the exact approved wording, or “please ask your practitioner”. If no reply: why. For a possible adverse event: whether it is serious, whether it was reported to FDA and when (serious reports are due within 15 business days of receipt).',
                'now'   => 'Saved on the response with your name and the time, and copied into the closing note of the compliance task.',
                'later' => 'Shown to the coordinator as **Compliance guidance** above the reply box — the reply uses only this wording. Also visible in Tasks → Closed.',
                'watch' => 'There are no separate fields for “serious adverse event” or the report date, and the system does not track the 15-business-day FDA deadline — write it all here. Contact details are not removed from this note; leave out names and order details.',
            ],
        ],
    ],
    'response-reply' => [
        'page'    => 'marketing-performance',
        'form'    => 'Response → I replied on the platform',
        'open'    => ['marketing-performance', 'inbox.php'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records that someone replied on the platform itself. The portal does not post replies — reply on the social channel or by email first, then record it here.',
        'note'    => '**I replied on the platform** marks the response Replied. It only shows once the response is Open: triaged and, if it was escalated, cleared by compliance.',
        'fields'  => [
            [
                'field' => 'What we replied',
                'enter' => 'Optional, up to 2,000 characters: a short summary or the reply text.',
                'now'   => 'Emails, phone numbers and @handles are replaced with [email], [phone] and [handle], then it is shown on the response with your name and the time.',
                'later' => 'The response drops out of the coordinator’s reply task and the Monday digest’s awaiting-reply count. No job reads the text itself.',
                'watch' => 'Names are not removed — don’t include the person’s name. If compliance gave guidance, what you posted must match it.',
            ],
        ],
    ],
    'response-actions' => [
        'page'    => 'marketing-performance',
        'form'    => 'Response → Set label / Close without reply',
        'open'    => ['marketing-performance', 'inbox.php?tab=action'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Corrects the AI’s label by hand, sends a response to compliance yourself, or closes a response that needs no reply.',
        'note'    => '**Set label** saves the label; **Claims risk** or **Possible adverse event** sends it to compliance straight away. **Re-run AI triage** asks the AI again and replaces the current label, even one set by hand. **Close without reply** closes it. **Reopen** (on replied or closed responses) puts it back to Open.',
        'fields'  => [
            [
                'field' => 'Label',
                'enter' => '**Possible adverse event**, **Claims risk**, **Complaint**, **Question**, **Praise**, **Spam** or **Other**. While a response is with compliance only the first two are offered.',
                'now'   => 'Saved as “set by hand”. Claims risk or Possible adverse event: the response goes to compliance, the deadline clock starts (24 hours by default; an already-escalated response keeps its deadline), a high-priority compliance task opens and compliance reviewers are emailed. Any other label: the response becomes Open.',
                'later' => 'Question and Complaint put it in the coordinator’s reply task (a complaint makes that task high priority) and the digest’s awaiting-reply count. On the linked asset’s score, Praise and Question earn positive-response points, Claims risk, Adverse event and Complaint count as risk responses, and Spam is left out.',
                'watch' => 'Only compliance can take a response out of escalation — you can’t relabel it to something milder. Reopen a replied or closed response before changing its label. A response escalated once before is not emailed to compliance again.',
            ],
            [
                'field' => 'Why',
                'enter' => 'Optional, up to 1,000 characters: why you chose the label.',
                'now'   => 'Shown as **Why** on the response, replacing the AI’s explanation. Blank saves “Labeled by hand.”',
                'later' => '—',
                'watch' => 'Contact details are not removed from this box — keep names and details out.',
            ],
            [
                'field' => 'Reason',
                'enter' => 'Optional, up to 500 characters, next to **Close without reply**. Example: spam hidden on the platform.',
                'now'   => 'Emails, phone numbers and @handles are removed, then it is shown on the response as the closing reason.',
                'later' => 'The response leaves **Needs action**, the reply task and the digest’s awaiting-reply count.',
                'watch' => 'Not offered while the response is with compliance — compliance closes those with **No public reply**. Label spam as **Spam** first so it doesn’t count towards the post’s responses.',
            ],
        ],
    ],
    'metrics-enter' => [
        'page'    => 'marketing-performance',
        'form'    => 'Asset Metrics → Enter metrics',
        'open'    => ['marketing-performance', 'metrics.php'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records the numbers a post or email has earned so far, copied from the platform’s analytics until GoHighLevel is connected. Pick the asset first (scheduled and posted assets are listed); the form then shows social or email boxes to match its channel. An asset is scored once it is marked posted.',
        'note'    => 'Every number box takes a whole number (commas are fine, up to 9 digits); leave a box blank if the platform doesn’t show it. At least one number is required. **Save metrics** saves one entry for the date; scores recalculate nightly or with **Run scoring now** on the Scores tab. **Delete** in the history table removes an entry.',
        'fields'  => [
            [
                'field' => 'As of', 'req' => true,
                'enter' => 'The date you read the numbers, in Central time. Defaults to today; it cannot be in the future.',
                'now'   => 'Saving again for the same date replaces that day’s entry — boxes left blank are cleared.',
                'later' => 'Only the latest-dated entry for each asset is scored. On the same date an imported entry wins over a hand-entered one.',
                'watch' => 'Enter lifetime totals, not the change since last time. The latest entry replaces earlier ones completely: a blank box counts as zero, it does not fall back to an older number.',
            ],
            [
                'field' => 'Impressions',
                'enter' => 'Social only. Lifetime impressions.',
                'now'   => 'Shown on **Recent entries** (Impressions / sent).',
                'later' => 'Carried into the nightly score but earns no points.',
                'watch' => '—',
            ],
            [
                'field' => 'Reach',
                'enter' => 'Social only. Lifetime unique reach.',
                'now'   => 'Used in place of Impressions when Impressions is blank.',
                'later' => 'Earns no points.',
                'watch' => 'Fill Impressions when the platform shows it; Reach is only a fallback.',
            ],
            [
                'field' => 'Likes / reactions',
                'enter' => 'Social only. Lifetime likes or reactions.',
                'now'   => 'Saved with the entry.',
                'later' => 'Earns points on the asset’s score (0.5 each by default) and counts in its **Interactions**, which roll up to campaign, topic and interest scores and feed the Monday digest.',
                'watch' => '—',
            ],
            [
                'field' => 'Comments',
                'enter' => 'Social only. Lifetime comment count.',
                'now'   => 'Saved with the entry.',
                'later' => '1 point each by default; counts in Interactions.',
                'watch' => 'Responses logged in the Response Inbox are counted separately, so a comment can count both here and there.',
            ],
            [
                'field' => 'Shares / reposts',
                'enter' => 'Social only. Lifetime shares or reposts.',
                'now'   => 'Saved with the entry.',
                'later' => '2 points each by default; counts in Interactions.',
                'watch' => '—',
            ],
            [
                'field' => 'Saves',
                'enter' => 'Social only. Lifetime saves or bookmarks.',
                'now'   => 'Saved with the entry.',
                'later' => '1 point each by default; counts in Interactions.',
                'watch' => '—',
            ],
            [
                'field' => 'Link clicks',
                'enter' => 'Social only. Clicks on the post’s link as the platform reports them.',
                'now'   => 'Saved with the entry.',
                'later' => '0.5 points each by default. Not part of Interactions.',
                'watch' => 'Site visits from the tagged link come from GA4 automatically and score separately — enter the platform’s count here anyway.',
            ],
            [
                'field' => 'Video views',
                'enter' => 'Social only. Lifetime video views.',
                'now'   => 'Shown in the asset’s history.',
                'later' => '—',
                'watch' => 'Saved for reference; no score or report uses it at the moment.',
            ],
            [
                'field' => 'Sent',
                'enter' => 'Email only. Number of emails sent.',
                'now'   => 'Shown on **Recent entries** (Impressions / sent).',
                'later' => 'Earns no points.',
                'watch' => '—',
            ],
            [
                'field' => 'Delivered',
                'enter' => 'Email only. Number delivered.',
                'now'   => 'Shown in the asset’s history.',
                'later' => '—',
                'watch' => 'Saved for reference; no score or report uses it at the moment.',
            ],
            [
                'field' => 'Opens',
                'enter' => 'Email only. Total opens.',
                'now'   => 'Saved with the entry.',
                'later' => '0.2 points each by default; shown as **Email opens** on Scores.',
                'watch' => '—',
            ],
            [
                'field' => 'Clicks',
                'enter' => 'Email only. Total link clicks in the email.',
                'now'   => 'Saved with the entry.',
                'later' => '1 point each by default; shown as **Email clicks** on Scores and given to the Monday digest.',
                'watch' => '—',
            ],
            [
                'field' => 'Replies',
                'enter' => 'Email only. Replies received.',
                'now'   => 'Saved with the entry.',
                'later' => '3 points each by default.',
                'watch' => 'Replies you also log in the Response Inbox count again there.',
            ],
            [
                'field' => 'Unsubscribes',
                'enter' => 'Email only. Unsubscribes from this send.',
                'now'   => 'Shown in the asset’s history.',
                'later' => '—',
                'watch' => 'Saved for reference; it does not lower the score and no report uses it at the moment.',
            ],
            [
                'field' => 'Bounces',
                'enter' => 'Email only. Bounced addresses.',
                'now'   => 'Shown in the asset’s history.',
                'later' => '—',
                'watch' => 'Saved for reference; it does not lower the score and no report uses it at the moment.',
            ],
            [
                'field' => 'Leads',
                'enter' => 'Social and email. Leads the platform attributes to this post or email.',
                'now'   => 'Shown on **Recent entries**.',
                'later' => '15 points each by default — the most heavily weighted number you can enter.',
                'watch' => 'One lead is worth as much as 30 likes by default, so check the figure before saving.',
            ],
            [
                'field' => 'Note',
                'enter' => 'Optional, up to 500 characters. Example: copied from LinkedIn analytics.',
                'now'   => 'Shown under your name in the asset’s history.',
                'later' => '—',
                'watch' => 'Saved for reference; no job reads it.',
            ],
        ],
    ],
    'metrics-import' => [
        'page'    => 'marketing-performance',
        'form'    => 'Asset Metrics → Import CSV',
        'open'    => ['marketing-performance', 'metrics.php?tab=import'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Loads many metric entries at once from a spreadsheet or platform export, pasted as CSV text. Each row becomes one entry, scored exactly like one typed on Enter metrics.',
        'note'    => 'Columns (header names are not case-sensitive; spaces and dashes count as underscores): **asset_id** or **external_post_id** (the GoHighLevel ID saved on the calendar) – one is required; **as_of** or **date** – required, YYYY-MM-DD or M/D/YYYY; then any of **impressions**, **reach**, **likes** or **reactions**, **comments**, **shares** or **reposts**, **saves**, **link_clicks** or **clicks**, **video_views** or **views**, **sent** or **email_sent**, **delivered**, **opens** or **email_opens**, **email_clicks**, **replies**, **unsubscribes**, **bounces**, **leads**. Other columns are ignored.',
        'fields'  => [
            [
                'field' => 'CSV', 'req' => true,
                'enter' => 'Paste the header row, then one row per asset and date. Example: asset_id,as_of,impressions,likes,comments,shares on the first line and 12,2026-10-05,840,31,4,2 on the next.',
                'now'   => 'Each row is matched to a scheduled or posted asset and saved as an imported entry noted “CSV import”. Re-importing the same asset and date replaces the earlier import. Good rows are saved even when others fail; up to 50 problems are listed by line number.',
                'later' => 'Imported entries are scored nightly like typed ones; on the same date an import wins over a hand entry, and the latest date always wins.',
                'watch' => 'A **clicks** column is read as social link clicks — use **email_clicks** for email. Put numbers with commas in quotes or the row splits. Rows for assets that aren’t scheduled or posted, future dates and rows with no numbers are skipped. Without asset_id (or external_post_id) and as_of in the header nothing imports.',
            ],
        ],
    ],
    'task-new' => [
        'page'    => 'marketing-tasks',
        'form'    => 'Tasks → New task',
        'open'    => ['marketing-tasks', '?tab=new'],
        'who'     => 'Anyone with Marketing Update access',
        'purpose' => 'Adds a manual task to the marketing work queue for anything the automatic tasks don’t cover. Automatic tasks (briefs, reviews, publishing, scheduling, replies, compliance) open and close by themselves — don’t duplicate them here.',
        'note'    => '**Create task** saves it and opens **All open**. Nobody is emailed — tell the person yourself.',
        'fields'  => [
            [
                'field' => 'Task', 'req' => true,
                'enter' => 'A short action, up to 300 characters. Example: Update the LinkedIn banner for the October campaign.',
                'now'   => 'The task’s name in the queue; it becomes a link when Link is filled.',
                'later' => '—',
                'watch' => 'Blank gives “Give the task a title.”',
            ],
            [
                'field' => 'Assignee',
                'enter' => 'Pick a person with Marketing access, or leave **Unassigned**.',
                'now'   => 'Puts the task in that person’s **My tasks**.',
                'later' => 'Can be changed later from the task list.',
                'watch' => 'No email or notification is sent.',
            ],
            [
                'field' => 'Role',
                'enter' => '**Any**, **Writer**, **Compliance**, **Editorial** or **Coordinator**.',
                'now'   => 'An unassigned task shows in **My tasks** for everyone holding the role: Writer and Coordinator – anyone with Update access; Compliance – compliance reviewers; Editorial – Marketing admins.',
                'later' => 'Used by the role filter on the task list.',
                'watch' => 'With no assignee and role **Any**, the task is in nobody’s My tasks — it only shows under **All open**.',
            ],
            [
                'field' => 'Due',
                'enter' => 'Optional date.',
                'now'   => 'Shown on the task; once the date has passed it turns red and counts as overdue in the Queue banner.',
                'later' => 'Tasks with a due date are listed before those without.',
                'watch' => 'Manual tasks get no automatic deadline — the deadline days in Settings (tasks.sla_days) only apply to automatic tasks.',
            ],
            [
                'field' => 'Priority',
                'enter' => '**Normal** (default) or **High**.',
                'now'   => 'High tasks are listed first with a **High** badge.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Link',
                'enter' => 'Optional, up to 500 characters: a portal path starting with / (for example /marketing/content/view.php?id=3) or a full https:// address.',
                'now'   => 'Makes the task title a link.',
                'later' => '—',
                'watch' => 'Anything else is rejected: “The link must be a portal path (starting with /) or a full http(s) URL.”',
            ],
            [
                'field' => 'Detail',
                'enter' => 'Optional, up to 2,000 characters.',
                'now'   => 'Shown under the title in the list.',
                'later' => '—',
                'watch' => '—',
            ],
        ],
    ],
    'task-close' => [
        'page'    => 'marketing-tasks',
        'form'    => 'Tasks → Done / Cancel / Reopen, reassign',
        'open'    => ['marketing-tasks', '?tab=mine'],
        'who'     => 'Anyone with Marketing Update access',
        'purpose' => 'Closes manual tasks when they are finished or no longer needed, reopens closed ones, and moves any open task to another person. Automatic tasks close by themselves once the work is done.',
        'note'    => '**Done** and **Cancel** close the task with the note (if any) and move it to **Closed**. **Reopen** on a closed manual task puts it back in the queue and clears the note. Tasks from the Monday digest show as **Manual**, so close them here too.',
        'fields'  => [
            [
                'field' => 'Note (optional)',
                'enter' => 'Up to 500 characters, next to **Done** / **Cancel**: what was done or why it was cancelled.',
                'now'   => 'Saved with the task, your name and the time.',
                'later' => 'Shown as **Closing note** under the task in **Closed**. For digest tasks, **Done** adds to the “done” count on Engagement & Performance → Weekly digests.',
                'watch' => 'Cancelled digest tasks don’t count as done. Regenerating a digest cancels its open tasks.',
            ],
            [
                'field' => 'Assignee',
                'enter' => 'In the task list: pick a person or **Unassigned**. It saves as soon as you choose.',
                'now'   => 'Moves the open task — automatic or manual — to that person’s **My tasks**.',
                'later' => 'An automatic task keeps the new assignee for as long as it stays open.',
                'watch' => 'No notification is sent. Closed tasks can’t be reassigned.',
            ],
        ],
    ],
];
