<?php

declare(strict_types=1);

return [
    'interest' => [
        'page'    => 'research-interests',
        'form'    => 'New interest / Edit interest',
        'open'    => ['research-interests', 'edit.php'],
        'who'     => 'Marketing admin (Create access for new, Update access to edit)',
        'purpose' => 'Defines a subject the system watches. Everything in Research starts here: the scoring and clustering AI, the weekly AI research agent and the Keyword Universe all read these fields.',
        'fields'  => [
            [
                'field' => 'Name', 'req' => true,
                'enter' => 'A short, plain name for the subject, up to 150 characters. Example: **Berberine evidence**.',
                'now'   => 'Labels the interest on items, topics and scores. Given to the scoring and clustering AI as the name of the interest.',
                'later' => 'Engagement scores roll up under it (Engagement & Performance → Scores, interest level).',
                'watch' => 'Must be unique. Renaming keeps all history — it is the same record.',
            ],
            [
                'field' => 'Description',
                'enter' => 'One or two sentences: what we want to learn and why it matters to NutraAxis. Example: human trials of berberine for glucose metabolism and how it compares with metformin.',
                'now'   => 'Sent to the scoring and clustering AI and to the research agent as context. A specific description gives sharper relevance scores.',
                'later' => '—',
                'watch' => 'Write it for the AI: specific beats broad ("human clinical trials" rather than "research").',
            ],
            [
                'field' => 'Therapeutic area',
                'enter' => 'Pick from the list (set by admins in Admin & Jobs → Settings, taxonomy.therapeutic_areas).',
                'now'   => 'Added to the interest’s description for the scoring prompt and the research agent.',
                'later' => '—',
                'watch' => 'If the right area is missing, ask an admin to add it in Settings rather than choosing a near match.',
            ],
            [
                'field' => 'Product line',
                'enter' => 'Pick from the list (Settings, taxonomy.product_lines), or leave blank for general science.',
                'now'   => 'Added to the interest’s description for the research agent.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Audience',
                'enter' => 'Pick who the evidence is for (Settings, brand.audiences).',
                'now'   => 'Tells the research agent whose questions to answer. Blank means practitioners.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Priority (1–5)',
                'enter' => 'A number from 1 (low) to 5 (high). New interests start at 3.',
                'now'   => 'Higher-priority interests are researched first by the daily agent and listed first to the scoring AI.',
                'later' => 'The daily engagement job suggests moving it up or down one step when its engagement score is well above or below the others; **Apply suggested priority** accepts it.',
                'watch' => 'Keep most interests at 3 and save 5 for the current campaign focus, or the ordering stops meaning anything.',
            ],
            [
                'field' => 'Status',
                'enter' => '**Active**, **Paused** or **Retired**.',
                'now'   => 'Only Active interests are scored against, clustered and researched. Paused stops all of that but keeps everything; Retired is for subjects you are finished with.',
                'later' => 'Topics, items and scores from a paused or retired interest stay in reports.',
                'watch' => 'Pause rather than delete when a subject is seasonal.',
            ],
            [
                'field' => 'Run the weekly AI research agent',
                'enter' => 'Tick to include this interest in the AI research agent (ticked by default).',
                'now'   => 'The agent runs daily at 06:00 and covers each ticked interest about once a week, searching the web and adding verified finds to the item queue. Each run costs a few cents of AI spend.',
                'later' => '—',
                'watch' => 'Untick for interests that your feeds already cover well, to save AI spend.',
            ],
            [
                'field' => 'Include terms', 'req' => 'This or Search queries',
                'enter' => 'One term per line, up to 300 characters each — the words papers and people actually use. Example: berberine, AMPK activation, insulin sensitivity.',
                'now'   => 'Each term is added to the Keyword Universe automatically. The first 12 are given to the scoring and clustering AI as this interest’s vocabulary, and all are sent to the research agent.',
                'later' => 'Keyword research, the Keyword map and page targeting work from the Keyword Universe entries these create.',
                'watch' => 'You need at least one include term **or** one search query. One idea per line — commas are not separators.',
            ],
            [
                'field' => 'Exclude terms',
                'enter' => 'One per line: subjects that look related but are not. Example: berberine eye drops.',
                'now'   => 'The research agent is told to skip results about these.',
                'later' => '—',
                'watch' => 'Relevance scoring of harvested feed items does **not** use exclude terms — to stop a feed bringing in off-topic items, fix or pause the source.',
            ],
            [
                'field' => 'Hashtags',
                'enter' => 'One per line, with or without the #.',
                'now'   => 'Saved with the interest for reference (for example when writing social posts).',
                'later' => '—',
                'watch' => 'No scheduled job reads these at the moment.',
            ],
            [
                'field' => 'Search queries', 'req' => 'This or Include terms',
                'enter' => 'One per line, written as you would type them into Google Scholar. Example: berberine randomized controlled trial 2025.',
                'now'   => 'The research agent runs these web searches. With none, it uses its own judgement from the name and include terms.',
                'later' => '—',
                'watch' => 'Required only if there are no include terms. Keep each query narrow; broad queries return reviews and news rather than evidence.',
            ],
            [
                'field' => 'Sources',
                'enter' => 'Tick the feeds and sites that serve this interest.',
                'now'   => 'Links the sources to the interest. The research agent learns which domains to trust from items those sources harvested.',
                'later' => 'The interest’s source list helps you judge which feeds to keep or pause each month.',
                'watch' => 'Scoring checks every harvested item against every active interest, whether or not its source is ticked. Add a new source on the Sources tab first, then tick it here.',
            ],
        ],
    ],
    'source' => [
        'page'    => 'research-interests',
        'form'    => 'New source / Edit source',
        'open'    => ['research-interests', 'source.php'],
        'who'     => 'Marketing admin (Create access for new, Update access to edit)',
        'purpose' => 'Registers a feed, search or website for the Content Harvester to fetch. Fetching is plain code on a schedule – no AI and no AI spend; the scoring AI reads what comes in afterwards.',
        'note'    => '**Create source** saves it, and a new source runs on the next hourly harvest. **Pause** / **Resume** on the Sources tab switch a source off and on without opening it; resuming clears its failure count. **Add as source** on Content Harvester → Suggested sources opens this form pre-filled as a Site crawl of that domain’s home page.',
        'fields'  => [
            [
                'field' => 'Name', 'req' => true,
                'enter' => 'A short label, up to 150 characters. Example: **FDA press releases**.',
                'now'   => 'Names the source on the Sources tab, in harvest runs and in the item queue.',
                'later' => 'Given to the scoring AI as the source of every item this source brings in.',
                'watch' => 'Name the publisher or feed rather than the subject, so sources are easy to tell apart when you review which to keep.',
            ],
            [
                'field' => 'Type', 'req' => true,
                'enter' => '**RSS / Atom feed**, **Google News search**, **PubMed search**, **ClinicalTrials.gov search**, **Site crawl (listing page)**, **Reddit (RSS)** or **YouTube channel (RSS)**. The form then shows URL or Search query to match.',
                'now'   => 'Decides how the harvester fetches it. Feed and crawl types need a URL; the three search types need a search query.',
                'later' => 'The item queue can be filtered by source type.',
                'watch' => 'Google News returns the last 7 days only. PubMed and ClinicalTrials.gov look back 30 days.',
            ],
            [
                'field' => 'Schedule',
                'enter' => '**Hourly**, **Daily** (default) or **Weekly**.',
                'now'   => 'The harvest job runs every hour and fetches each source that is due. After each run the next one is booked 1 hour, 24 hours or 7 days later.',
                'later' => '—',
                'watch' => 'Changing the schedule takes effect after the run already booked. Hourly suits busy news feeds only; duplicates are skipped either way, so fetching more often gains little.',
            ],
            [
                'field' => 'URL', 'req' => 'For feed and crawl types',
                'enter' => 'The full address starting with https://, up to 2,000 characters. Feeds: the feed address, e.g. https://www.reddit.com/r/Supplements/.rss. Site crawl: the site’s news or blog listing page.',
                'now'   => 'Fetched on each run – up to 50 new entries a run. Anything already in the queue, by address or near-identical text, is skipped as a duplicate.',
                'later' => 'Content Harvester → Suggested sources stops suggesting a domain once it appears in a source’s URL.',
                'watch' => 'Save fails with “A valid URL is required for this source type” if the address is not a valid URL. An ordinary web page is not a feed – feed types fail on each run if the address does not return RSS, Atom or RDF. Site crawls check robots.txt and fail if our crawler is not allowed on the listing page.',
            ],
            [
                'field' => 'Search query', 'req' => 'For search types',
                'enter' => 'The search, up to 1,000 characters. PubMed takes its own syntax, e.g. berberine AND (glucose OR insulin).',
                'now'   => 'Google News: results from the last 7 days. PubMed: the newest papers added in the last 30 days, with abstracts. ClinicalTrials.gov: studies updated in the last 30 days.',
                'later' => '—',
                'watch' => 'Required for the three search types (“A search query is required for this source type”). A broad query fills the queue with items the scoring AI then discards as not relevant – and each one still costs a little scoring spend.',
            ],
            [
                'field' => 'Article link pattern',
                'enter' => 'Site crawl only, optional. A regular expression matched against each link’s full address, not case-sensitive. Example: /news/\d{4}/. Blank takes links nested under the listing page’s own path.',
                'now'   => 'Picks which links on the listing page are articles. Only links on the same site count; images, PDFs and media files are skipped.',
                'later' => '—',
                'watch' => 'An invalid pattern is refused on save (“Link pattern is not a valid regular expression”). With a home-page URL and no pattern, almost every link on the site qualifies – set a pattern or point the URL at the listing page.',
            ],
            [
                'field' => 'Max new pages per run',
                'enter' => 'Site crawl only. A number from 1 to 25; default 10.',
                'now'   => 'The most new article pages fetched from the listing on each run, with a pause of about 1.5 seconds between pages. Links already in the queue don’t count towards it.',
                'later' => '—',
                'watch' => 'Numbers outside 1–25 are pulled back into range. Keep it low for small sites.',
            ],
            [
                'field' => 'Status',
                'enter' => '**Active** (default), **Paused** or **Auto-paused (failing)**.',
                'now'   => 'Only Active sources are fetched. Setting a paused or auto-paused source back to Active clears its failure count and runs it on the next hourly harvest.',
                'later' => 'After 5 failed runs in a row (the default in Admin & Jobs → Settings) the harvester sets the source to Auto-paused itself; auto-paused sources are listed first on the Sources tab.',
                'watch' => 'Choose **Paused** to stop a source by hand – Auto-paused is meant for the harvester. Read Last error under Health before resuming a failing source.',
            ],
            [
                'field' => 'Terms-of-use notes',
                'enter' => 'Free text: usage limits, attribution rules or restrictions from the site’s terms.',
                'now'   => 'Saved with the source for reference.',
                'later' => '—',
                'watch' => 'No job reads these and the harvester does not enforce them – check them yourself before quoting or reusing a source’s text.',
            ],
            [
                'field' => 'Interests',
                'enter' => 'Tick the interests this source serves.',
                'now'   => 'Links the source to those interests. It counts in each interest’s sources and 7-day items, and filtering the item queue by interest shows its items.',
                'later' => 'The research agent learns which domains to trust for an interest from items its linked sources harvested.',
                'watch' => 'Scoring checks every item against every active interest, ticked or not. The same links can be set from the interest form’s Sources list.',
            ],
        ],
    ],
    'taxonomy' => [
        'page'    => 'research-interests',
        'form'    => 'Taxonomy',
        'open'    => ['research-interests', '?tab=taxonomy'],
        'who'     => 'Marketing admin (Update access)',
        'purpose' => 'The shared pick-lists behind the interest form and topic briefs, and the vocabulary the research AI must answer in. Changes apply to the forms at once and to the AI from its next run.',
        'note'    => '**Save taxonomy** saves all three lists together and reports how many changed. Without Update access the lists are read-only.',
        'fields'  => [
            [
                'field' => 'Therapeutic areas',
                'enter' => 'One area per line, written as it should appear. Example: **Metabolic and Weight Health**. Blank lines are ignored.',
                'now'   => 'Fills the Therapeutic area list on interests, topic briefs and Claims Matrix products. The scoring AI tags each item with areas from this list, and the clustering AI gives each new topic one.',
                'later' => 'The Topic Board and Scored items tabs filter by area.',
                'watch' => 'Renaming or removing an area does not update records that already use it, and saving a topic brief clears an area that is no longer listed. The AI’s answers must match a line exactly (case aside), so keep names stable.',
            ],
            [
                'field' => 'Product lines',
                'enter' => 'One per line – product names or ranges.',
                'now'   => 'Fills the Product line list on the interest form.',
                'later' => 'An interest’s product line is passed to the research agent as context.',
                'watch' => 'Only the interest form uses this list. Products for claims and content come from the Claims Matrix, not from here.',
            ],
            [
                'field' => 'Audiences (key|description)',
                'enter' => 'One per line as key|description. Example: practitioner|Healthcare practitioners and clinic owners.',
                'now'   => 'Fills the Audience list on the interest form: the description is shown, the key is saved and passed to the research agent.',
                'later' => 'Campaign and content AI prompts look up the description by key – **practitioner** and **consumer** match the Audience choice on topics, campaigns and pieces, and **Both** sends every line.',
                'watch' => 'Keep the keys **practitioner** and **consumer** exactly; edit only the text after the |. A renamed key stops matching, and the AI then gets every audience line instead of the one chosen.',
            ],
        ],
    ],
    'item-add' => [
        'page'    => 'research-harvester',
        'form'    => 'Add item',
        'open'    => ['research-harvester', '?tab=add'],
        'who'     => 'Coordinator (Create access)',
        'purpose' => 'Puts one article, paper or post into the item queue by hand – something a colleague sent, or text from a newsletter or PDF the harvester can’t reach. From there it is scored and grouped into topics like any harvested item.',
        'note'    => '**Add to queue** saves it straight away. It is scored in the next scoring batch, which goes once 25 items are waiting or the oldest has waited 12 hours, or when someone presses **Score waiting items** on Topic Synthesis. In the Item queue, **Ignore** keeps a new or scored item out of scoring and topics; **Restore** sends it back to be scored again.',
        'fields'  => [
            [
                'field' => 'URL', 'req' => true,
                'enter' => 'The full address of the article, study or post, starting with http:// or https://.',
                'now'   => 'Checked against everything already in the queue, ignoring tracking tags (utm_…), “www.” and a trailing slash. If Title or Summary is blank, the page is fetched to fill them in.',
                'later' => 'The harvesters and the research agent skip this address from now on.',
                'watch' => '“That URL is already in the queue” means it is there already – search the Item queue instead. Pages behind a login can’t be read, so enter Title and Summary yourself.',
            ],
            [
                'field' => 'Title',
                'enter' => 'Up to 500 characters. Leave blank to use the page’s own title.',
                'now'   => 'Shown in the queue and given to the scoring AI.',
                'later' => 'Shown on the topic the item joins, and listed to the campaign and content AI when the item is used as evidence.',
                'watch' => 'If the page title can’t be read, the save fails (“Could not read a title from that page — enter one manually.”).',
            ],
            [
                'field' => 'Summary / why it matters',
                'enter' => 'A few sentences on what it reports and why it matters to us. Leave blank to use the page’s description. Saved up to 4,000 characters.',
                'now'   => 'Shown under the title in the queue. The scoring AI reads it first; together with Pasted text it reads about the first 1,800 characters.',
                'later' => 'The scoring AI writes its own one-line summary; that summary, not this text, is what topics and the campaign and content AI see.',
                'watch' => 'This text goes to the AI provider – no customer names, contact details or order information.',
            ],
            [
                'field' => 'Pasted text (optional)',
                'enter' => 'The article text, for closed groups, PDFs or newsletters. No length limit on the form.',
                'now'   => 'Saved with the item. The scoring AI reads it after the summary, within the same limit of about 1,800 characters.',
                'later' => 'Not shown anywhere and not used after scoring.',
                'watch' => 'Only the opening is read, so paste the abstract or key findings first. Text from closed groups often contains members’ names – remove them, because it goes to the AI provider.',
            ],
            [
                'field' => 'Interest',
                'enter' => 'Pick the interest it belongs to, or —. The list includes paused and retired interests.',
                'now'   => 'Tags the item with that interest, so it shows when the queue is filtered by it.',
                'later' => 'The research agent counts the item’s domain among the interest’s trusted domains.',
                'watch' => 'It does not decide relevance. The scoring AI still scores the item against every active interest, and an item that scores below the relevance threshold (0.6) is discarded even though you added it – discarded items can’t be restored from the queue.',
            ],
        ],
    ],
    'topic-brief' => [
        'page'    => 'research-topics',
        'form'    => 'Topic → Brief and decision',
        'open'    => ['research-topics', '?tab=board'],
        'who'     => 'Marketing admin (Update access)',
        'purpose' => 'Turns an AI-proposed topic into the brief that Campaign Studio and the Content Pipeline write from, and records whether you accept, park or reject it. Title, summary and why it matters start as the clustering AI’s draft; angle, audience and avoid are yours.',
        'note'    => '**Save brief** saves the fields without changing status. **Save and accept** saves, then accepts – it needs an angle. **Park**, **Reject** and **Reopen** change the status and record the decision note only; other edits are not saved. Parking or rejecting an accepted topic blocks campaign generation and AI briefs and drafts for its pieces until it is accepted again. Under Items, **Mark as evidence** puts an item first (up to 8) in the evidence given to the campaign and content AI – with none marked, the most relevant items are used – and **Remove** returns an item to the pool for the next clustering run. The Topic Board list has the same Park, Reject and Reopen buttons (no note), plus **Score waiting items** and **Cluster topics now** to run those jobs immediately.',
        'fields'  => [
            [
                'field' => 'Title', 'req' => true,
                'enter' => 'Up to 300 characters; starts as the AI’s wording. Say plainly what the topic is about.',
                'now'   => 'Names the topic on the board. The clustering AI sees it, with the interest, in its list of open topics when deciding whether new items extend this topic rather than start a new one.',
                'later' => 'Sent to the AI as the topic title for campaigns and long-form pieces. New campaign names and a piece’s default working title come from it.',
                'watch' => 'Keep it specific – vague titles make it harder for the clustering AI to match new items to the right topic.',
            ],
            [
                'field' => 'Summary',
                'enter' => 'Up to 2,000 characters: what the items show, in neutral terms.',
                'now'   => 'Shown under the title on the board, and searchable there.',
                'later' => 'Sent to the AI as the topic summary for campaign generation and content briefs.',
                'watch' => 'Stick to what the evidence reports – this text feeds generated copy.',
            ],
            [
                'field' => 'Why it matters',
                'enter' => 'One sentence, up to 1,000 characters.',
                'now'   => 'Shown as the lead line under the topic title on this page.',
                'later' => 'Sent to the AI with the summary for campaign generation and content briefs.',
                'watch' => '—',
            ],
            [
                'field' => 'Interest',
                'enter' => 'Pick the watched interest this topic belongs to, or —. The list includes paused and retired interests.',
                'now'   => 'Filters the board by interest, and is shown to the clustering AI with the title.',
                'later' => 'Engagement scores of campaigns and pieces from this topic roll up to this interest (Engagement & Performance → Scores).',
                'watch' => 'Emerging topics have no interest. If the theme is worth watching, use **Create interest** first, then pick it here.',
            ],
            [
                'field' => 'Therapeutic area',
                'enter' => 'Pick from the Taxonomy list, or —.',
                'now'   => 'Filters the Topic Board by area.',
                'later' => '—',
                'watch' => 'Only areas on the current Taxonomy list are kept; an area that has since been renamed or removed is cleared when you save.',
            ],
            [
                'field' => 'Angle', 'req' => 'To accept',
                'enter' => 'Up to 2,000 characters: the specific point of view our content takes, and for whom. Example: what the 2026 berberine trials mean for practitioners already using GLP-1s – tolerability and timing, not weight-loss promises.',
                'now'   => 'Required to accept (“Write the angle before accepting…”), and an accepted topic can’t be saved without one. Shown on the Accepted tab and searchable.',
                'later' => 'The main instruction to the AI for campaign generation and content briefs. A campaign falls back to its own extra brief only when the topic has no angle.',
                'watch' => 'This text goes to the AI provider – no customer names, contact details or order information. Editing it later changes only copy generated afterwards.',
            ],
            [
                'field' => 'Audience',
                'enter' => '**Both**, **Practitioner**, **Consumer**, or —.',
                'now'   => 'Saved on the topic.',
                'later' => 'The default audience when a campaign or long-form piece is started from this topic without choosing one; — means Both.',
                'watch' => 'Only a default – each campaign and piece keeps its own audience once created.',
            ],
            [
                'field' => 'Avoid',
                'enter' => 'Up to 1,000 characters: claims, comparisons or framings the content must not use. Example: no comparison with metformin; no weight-loss language.',
                'now'   => 'Saved on the topic.',
                'later' => 'Sent to the AI as things to avoid in campaign generation and content briefs.',
                'watch' => 'It steers the writing AI only; the claims check does not read it. Words that must always be flagged belong in the claims flag terms (Admin & Jobs → Settings).',
            ],
            [
                'field' => 'Decision note',
                'enter' => 'Optional, up to 500 characters: why you accepted, parked or rejected it.',
                'now'   => 'Saved with **Save and accept**, **Park**, **Reject** or **Reopen**, and shown in the Decided line at the top. **Save brief** ignores it, and a blank note keeps the previous one.',
                'later' => '—',
                'watch' => 'Kept for the record only; no job or report reads it.',
            ],
        ],
    ],
    'topic-claim-link' => [
        'page'    => 'research-topics',
        'form'    => 'Topic → Link claim',
        'open'    => ['research-topics', '?tab=board'],
        'who'     => 'Marketing admin (Update access)',
        'purpose' => 'Chooses the approved Claims Matrix wording that content on this topic may use. For campaigns, the linked claims are the only benefit statements the AI may write and the claims check will accept.',
        'note'    => '**Link claim** adds the claim to the Linked claims table; **Unlink** removes one. The form only shows while there are approved claims not yet linked.',
        'fields'  => [
            [
                'field' => 'Link claim', 'req' => true,
                'enter' => 'Pick an approved claim. **Tagged products** lists claims for products the scoring AI found in this topic’s items; **Other products** lists the rest.',
                'now'   => 'Links the claim to the topic. Only approved claims can be linked.',
                'later' => 'Campaign generation and the campaign claims check use only these claims; with none linked, the AI is told to make no product or ingredient benefit claims. Long-form pieces use these plus every approved claim of the piece’s product. A claim that is later retired drops out automatically.',
                'watch' => 'Copy already generated is not rewritten – the new list applies from the next generation or claims check.',
            ],
        ],
    ],
    'topic-merge' => [
        'page'    => 'research-topics',
        'form'    => 'Topic → Merge',
        'open'    => ['research-topics', '?tab=board'],
        'who'     => 'Marketing admin (Update access)',
        'purpose' => 'Folds a duplicate topic into another. Its items (with their evidence marks) and claim links move to the chosen topic, and this topic becomes Merged and read-only.',
        'note'    => '**Merge** asks you to confirm first. There is no unmerge in the portal.',
        'fields'  => [
            [
                'field' => 'Merge this topic into', 'req' => true,
                'enter' => 'Pick the topic to keep. The list shows up to 150 proposed, accepted and parked topics, most recently updated first, with their status.',
                'now'   => 'Moves the items and claim links (skipping any already there), recalculates the kept topic’s item counts and trend score, and opens it.',
                'later' => 'The kept topic’s brief and status do not change. Campaigns and pieces linked to the merged topic stay linked to it, and campaign generation and AI briefs and drafts for them are blocked because it is no longer accepted.',
                'watch' => 'Nothing from this topic’s brief is copied – move any angle or avoid notes worth keeping before you merge. Merge into the topic that already has the better brief.',
            ],
        ],
    ],
];
