<?php

declare(strict_types=1);

return [
    'keyword' => [
        'page'    => 'marketing-keywords',
        'form'    => 'Add keyword / Edit keyword',
        'open'    => ['marketing-keywords', ''],
        'who'     => 'Marketing admin (Create access for new, Update access to edit)',
        'purpose' => 'Keeps one list of the search phrases we want to rank for. The Content Pipeline picks its target keyword from this list, and Page Inventory links hand-mapped page keywords back to it. Interest include terms land here automatically.',
        'fields'  => [
            [
                'field' => 'Keyword', 'req' => true,
                'enter' => 'The phrase as people type it into Google, up to 200 characters. Example: **berberine for blood sugar**.',
                'now'   => 'Saved to the Keyword Universe and offered in the **Keyword list** on Content Pipeline → New piece and on a piece’s details.',
                'later' => 'Choosing it on a piece fills the piece’s primary keyword, which the AI brief is written around; once the piece is published, that keyword is mapped to its page in Page Inventory. A keyword added by hand to a page with the same wording is linked to this entry.',
                'watch' => 'Must be unique – you will see “That keyword already exists.” Renaming does not change pieces already created (they keep the wording they were given). If the keyword came from an interest’s include terms, the next save of that interest adds the original wording back.',
            ],
            [
                'field' => 'Purpose',
                'enter' => '**SEO**, **Interest** or **Both**. New keywords start as SEO.',
                'now'   => 'Shown in the list and used by the Purpose filter.',
                'later' => 'If an interest later lists the same term as an include term, an SEO keyword switches to Both automatically.',
                'watch' => 'Setting **Interest** here does not link the keyword to an interest – only an interest’s include terms do that (see the Interests column). No job reads this field.',
            ],
            [
                'field' => 'Priority (1–5)',
                'enter' => 'A whole number from 1 (low) to 5 (high). Defaults to 3; anything outside 1–5 is pulled back into range.',
                'now'   => 'Sorts the Keyword Universe list, highest first.',
                'later' => 'Also orders the **Keyword list** on Content Pipeline pieces, so high-priority keywords sit at the top.',
                'watch' => 'This is separate from an interest’s priority – it does not change what the research agent looks at first.',
            ],
            [
                'field' => 'Cluster',
                'enter' => 'Optional group name, up to 100 characters. Example: **blood sugar**.',
                'now'   => 'Shown in the list and found by Search. Shown after the keyword in the Content Pipeline → New piece **Keyword list** (“berberine for blood sugar — blood sugar”).',
                'later' => '—',
                'watch' => 'Free text – spell a cluster the same way every time. Nothing groups or totals keywords by cluster at the moment.',
            ],
            [
                'field' => 'Intent',
                'enter' => 'Optional, up to 20 characters. Suggested values: **info**, **commercial** or **nav**.',
                'now'   => 'Shown in the list.',
                'later' => '—',
                'watch' => 'Not checked against a list, and no job or AI prompt reads it at the moment.',
            ],
            [
                'field' => 'Monthly volume',
                'enter' => 'Optional whole number, 0 or more – average monthly searches from your keyword tool.',
                'now'   => 'Shown in the list.',
                'later' => '—',
                'watch' => 'Typed by hand and never refreshed automatically; update it when you re-research the keyword.',
            ],
            [
                'field' => 'Difficulty',
                'enter' => 'Optional score from 0 to 100, from your keyword tool.',
                'now'   => 'Shown in the list.',
                'later' => '—',
                'watch' => 'Typed by hand and never refreshed automatically. No job reads it.',
            ],
            [
                'field' => 'Status',
                'enter' => '**Active**, **Paused** or **Retired**. New keywords start Active.',
                'now'   => 'Shown as a badge and used by the Status filter.',
                'later' => '—',
                'watch' => 'Status does not hide a keyword anywhere else – paused and retired keywords still appear in the Content Pipeline **Keyword list**.',
            ],
            [
                'field' => 'Notes',
                'enter' => 'Optional, up to 1,000 characters. Example: where the volume figure came from, or which page should own it.',
                'now'   => 'Saved with the keyword and found by Search.',
                'later' => '—',
                'watch' => 'Reference only; nothing else reads it.',
            ],
        ],
    ],
    'keyword-import' => [
        'page'    => 'marketing-keywords',
        'form'    => 'Import CSV',
        'open'    => ['marketing-keywords', ''],
        'who'     => 'Marketing admin (Create access – needed even when the file only updates existing keywords)',
        'purpose' => 'Adds or updates many keywords at once from a spreadsheet export, for example after a keyword research session.',
        'note'    => '**Import** reads the file straight away and reports how many keywords were created, updated and skipped.',
        'fields'  => [
            [
                'field' => 'Import CSV', 'req' => true,
                'enter' => 'A .csv file with a header row. Columns: **keyword** (required), **purpose** (seo, interest or both), **priority**, **cluster**, **intent**, **volume**, **difficulty**, **notes**. A **status** column (active, paused or retired) is also read if present. Column order does not matter.',
                'now'   => 'Each row is matched on the keyword: new keywords are created, existing ones are updated. Rows with no keyword, or that fail to save, are counted as skipped.',
                'later' => 'Same as adding keywords by hand – they appear in the Content Pipeline **Keyword list** straight away.',
                'watch' => 'An update replaces **every** field with what is in the file: a missing or blank column resets that field (priority back to 3, purpose to SEO, status to Active; cluster, intent, volume, difficulty and notes cleared). To change one field, edit the keyword instead or export all columns first. Use lower-case values (seo, active) – anything else falls back to the default. The form’s length limits are not applied: a cluster over 100, intent over 20 or notes over 1,000 characters stops the import with an error part-way, keeping the rows before it.',
            ],
        ],
    ],
    'page-add' => [
        'page'    => 'marketing-pages',
        'form'    => 'Pages → Add a page',
        'open'    => ['marketing-pages', '?tab=pages'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Adds a live nutraaxislabs.com page that the sitemaps miss, so it is crawled, checked for SEO issues and gets its Search Console and GA4 numbers like every other page.',
        'note'    => '**Add and crawl** adds the page and crawls it at once, then opens its detail screen. **Crawl site now** (top of every tab) does the full Monday job on demand: reads the sitemaps, adds published Content Pipeline pieces and recrawls every active page.',
        'fields'  => [
            [
                'field' => 'Page URL', 'req' => true,
                'enter' => 'The full address starting with https://. Example: **https://www.nutraaxislabs.com/our-story**.',
                'now'   => 'Added to the inventory as “Added by hand”, with its page type set by the type rules in Admin & Jobs → Settings, then crawled. The crawl’s findings go straight into Audit & Issues. If the page is already in the inventory it is simply recrawled (and made Active again if it was excluded).',
                'later' => 'Recrawled with every active page each Monday. Search Console and GA4 numbers are matched to it by address. Its issues feed Audit & Issues, the daily alerts and the Monday digest’s pages-with-issues list.',
                'watch' => 'Only nutraaxislabs.com pages are accepted (with or without www). Anything after a **?** and a trailing slash are ignored, so every **/our-blog?post=…** address is the same page as /our-blog – individual blog posts cannot be added. You will see “Enter a full page URL starting with https://.” if the address is incomplete.',
            ],
        ],
    ],
    'page-keyword' => [
        'page'    => 'marketing-pages',
        'form'    => 'Page detail → Add keyword',
        'open'    => ['marketing-pages', '?tab=pages'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records which search phrases a page is meant to rank for, so the Keyword map can show gaps and pages competing for the same phrase.',
        'note'    => '**Map as secondary** next to a query under Search queries adds that query as a secondary keyword (source “From search queries”); **Remove** deletes a mapping. Other buttons on this screen: **Recrawl now** crawls the page again and updates its issues; **Exclude** adds a rule for this exact path to the exclusion list in Admin & Jobs → Settings so crawls skip it and it leaves the totals; **Include in inventory** undoes that, unless a broader exclusion rule still covers the page.',
        'fields'  => [
            [
                'field' => 'Add keyword', 'req' => true,
                'enter' => 'One search phrase, up to 200 characters. Example: **berberine for metabolic health**. It is saved in lower case with extra spaces removed.',
                'now'   => 'Added to the page’s Target keywords as “Added by hand”. Linked to the Keyword Universe entry with the same wording, if there is one.',
                'later' => 'Listed on the **Keyword map** tab. Search Console queries with the same wording show as **Mapped** on Engagement & Performance → Search and drop out of the unmapped-queries list the Monday digest works from.',
                'watch' => 'You will see “That keyword is already mapped to this page.” for a repeat. This does not add the keyword to the Keyword Universe or change the page itself – the title and copy still need editing on the website.',
            ],
            [
                'field' => 'Role',
                'enter' => '**Primary** (the default) or **Secondary**.',
                'now'   => 'Saved with the mapping; primary keywords list first.',
                'later' => 'A keyword that is primary on more than one active page is flagged “Also primary on N other pages” here and “Primary on N pages” on the Keyword map.',
                'watch' => 'Give each page one primary keyword and make sure no other page uses it as primary – two pages with the same primary compete with each other in Google. To change the role, remove the keyword and add it again.',
            ],
        ],
    ],
    'issue-openrush-import' => [
        'page'    => 'marketing-issues',
        'form'    => 'Audits → Import an OpenRush audit',
        'open'    => ['marketing-issues', '?tab=audits'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Adds the result of an OpenRush site audit, run in Cursor or Claude, to Audit & Issues alongside the portal’s own crawler findings.',
        'note'    => '**Import audit** runs the import straight away. **Crawl site now** on this tab runs the portal’s crawler over every active page (the same as the Monday audit). On the **Alerts** tab, **Check now** evaluates the alert rules and emails anything new, and **Acknowledge** marks an open alert as being handled – it still resolves itself once the cause is gone.',
        'fields'  => [
            [
                'field' => 'OpenRush audit_site result (JSON)', 'req' => true,
                'enter' => 'The whole, unedited JSON reply from OpenRush’s **audit_site** tool for nutraaxislabs.com (the full reply or just its data part). Up to 2 MB.',
                'now'   => 'Audited pages are matched to the Page Inventory by address; only active pages count and the rest are skipped. Each finding is added to an issue: checks the crawler also makes (such as missing title) join the crawler’s issue, and checks only OpenRush makes (such as low content) become their own “(OpenRush)” issues. Recorded on the Audits tab as a Sample audit with OpenRush’s score.',
                'later' => 'OpenRush-only issues resolve when a later import no longer flags that page; they cannot be marked fixed or rechecked by the crawler. New high-severity issues raise the daily site-issue alert.',
                'watch' => 'Errors you may see: not valid JSON; “That is not an OpenRush audit_site result” (no pages list); an audit for another domain; or none of its pages active in the inventory (“run a crawl first”). An import never clears the crawler’s own checks – only a crawl does. Importing the same audit twice only updates the last-seen dates.',
            ],
        ],
    ],
    'issue-fixed' => [
        'page'    => 'marketing-issues',
        'form'    => 'Issue → Mark fixed and recheck',
        'open'    => ['marketing-issues', '?tab=open'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records that a problem has been fixed on the website and immediately recrawls the pages still showing it, so the portal confirms the fix rather than taking it on trust.',
        'note'    => 'Shown only for New or Open issues found by the crawler; for OpenRush-only checks, run a fresh OpenRush audit and import it instead. Other buttons: **Acknowledge** moves a New issue to Open (and out of the triage task’s count); **Recheck pages now** recrawls the open pages without marking the issue fixed; **Generate fix spec** has the AI write a developer spec from the affected pages (about 30 seconds, a few cents of AI spend) – check it before sending, as it goes into the **Developer packet**.',
        'fields'  => [
            [
                'field' => 'Fix note',
                'enter' => 'Optional, up to 2,000 characters: what was changed and by whom. Example: titles shortened in document authoring by Sam, published 3 Oct.',
                'now'   => 'Saved with the issue and shown next to “Marked fixed” with your name and the time. The issue becomes **Fixed — rechecking** and the open pages are recrawled: if none still show the problem it moves to **Verified**, otherwise back to **Open** with a “Still present on N URL(s)” note.',
                'later' => 'If a later audit finds the problem again, the issue is reopened and its reopen count goes up.',
                'watch' => 'Mark fixed only after the change is published live – the recheck runs straight away. The crawler reads each page’s HTML before browser scripts run, so a fix made only by a script may not be seen. Marking fixed again replaces the earlier note. The note is not included in the CSV export or the developer packet.',
            ],
        ],
    ],
    'issue-triage' => [
        'page'    => 'marketing-issues',
        'form'    => 'Issue → Assignee / Ignore',
        'open'    => ['marketing-issues', '?tab=open'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Says who is dealing with an issue, or sets it aside with a reason when the finding is intended (for example, account pages that should stay out of Google).',
        'note'    => '**Save assignee** saves the choice. **Ignore** moves the issue to the Ignored tab; **Stop ignoring** on an ignored issue puts it back to Open, or to Verified if no pages still have it.',
        'fields'  => [
            [
                'field' => 'Assignee',
                'enter' => 'Pick someone with Marketing update access, or **Nobody**.',
                'now'   => 'Shown on the issue and in the Assignee column of the issue lists.',
                'later' => '—',
                'watch' => 'No email or task is sent to the person – tell them. Assigning does not change the status, so the triage task in Tasks keeps counting a New issue until someone acknowledges or ignores it.',
            ],
            [
                'field' => 'Ignore because', 'req' => true,
                'enter' => 'Why the finding is fine as it is, up to 1,000 characters. Example: **account pages are meant to be noindex**.',
                'now'   => 'The issue becomes **Ignored**. The reason is shown on the issue and on the Ignored tab, with who ignored it and when.',
                'later' => 'Audits keep tracking its pages, but it stays ignored even when found on new pages, and it is left out of the open list, the high-severity site-issue alert and the legacy brand alert.',
                'watch' => 'Required – leaving it blank gives an error. Ignoring does not remove the problem from the page’s issue badges in Page Inventory or from the Monday digest’s pages-with-issues list, which come straight from the crawl. Ignore intended findings only, not work you have not got to yet.',
            ],
        ],
    ],
];
