<?php

declare(strict_types=1);

return [
    'keyword' => [
        'page'    => 'marketing-keywords',
        'form'    => 'Add keyword / Edit keyword',
        'open'    => ['marketing-keywords', ''],
        'who'     => 'Marketing admin (Create access for new, Update access to edit)',
        'purpose' => 'Keeps one list of the search phrases we want to rank for. The Content Pipeline picks its target keyword from this list, and Page Inventory links hand-mapped page keywords back to it. Interest include terms land here automatically.',
        'fields'  => [
            [
                'field' => 'Keyword', 'req' => true,
                'enter' => 'The phrase as people type it into Google, up to 200 characters. Example: **berberine for blood sugar**.',
                'now'   => 'Saved to the Keyword Universe and offered in the **Keyword list** on Content Pipeline → New piece and on a piece’s details.',
                'later' => 'Choosing it on a piece fills the piece’s primary keyword, which the AI brief is written around; once the piece is published, that keyword is mapped to its page in Page Inventory. A keyword added by hand to a page with the same wording is linked to this entry.',
                'watch' => 'Must be unique – you will see “That keyword already exists.” Renaming does not change pieces already created (they keep the wording they were given). If the keyword came from an interest’s include terms, the next save of that interest adds the original wording back.',
            ],
            [
                'field' => 'Purpose',
                'enter' => '**SEO**, **Interest** or **Both**. New keywords start as SEO.',
                'now'   => 'Shown in the list and used by the Purpose filter.',
                'later' => 'If an interest later lists the same term as an include term, an SEO keyword switches to Both automatically.',
                'watch' => 'Setting **Interest** here does not link the keyword to an interest – only an interest’s include terms do that (see the Interests column). No job reads this field.',
            ],
            [
                'field' => 'Priority (1–5)',
                'enter' => 'A whole number from 1 (low) to 5 (high). Defaults to 3; anything outside 1–5 is pulled back into range.',
                'now'   => 'Sorts the Keyword Universe list, highest first.',
                'later' => 'Also orders the **Keyword list** on Content Pipeline pieces, so high-priority keywords sit at the top.',
                'watch' => 'This is separate from an interest’s priority – it does not change what the research agent looks at first.',
            ],
            [
                'field' => 'Cluster',
                'enter' => 'Optional group name, up to 100 characters. Example: **blood sugar**.',
                'now'   => 'Shown in the list and found by Search. Shown after the keyword in the Content Pipeline → New piece **Keyword list** (“berberine for blood sugar — blood sugar”).',
                'later' => '—',
                'watch' => 'Free text – spell a cluster the same way every time. Nothing groups or totals keywords by cluster at the moment.',
            ],
            [
                'field' => 'Intent',
                'enter' => 'Optional, up to 20 characters. Suggested values: **info**, **commercial** or **nav**.',
                'now'   => 'Shown in the list.',
                'later' => '—',
                'watch' => 'Not checked against a list, and no job or AI prompt reads it at the moment.',
            ],
            [
                'field' => 'Monthly volume',
                'enter' => 'Optional whole number, 0 or more – average monthly searches from your keyword tool.',
                'now'   => 'Shown in the list.',
                'later' => '—',
                'watch' => 'Typed by hand and never refreshed automatically; update it when you re-research the keyword.',
            ],
            [
                'field' => 'Difficulty',
                'enter' => 'Optional score from 0 to 100, from your keyword tool.',
                'now'   => 'Shown in the list.',
                'later' => '—',
                'watch' => 'Typed by hand and never refreshed automatically. No job reads it.',
            ],
            [
                'field' => 'Status',
                'enter' => '**Active**, **Paused** or **Retired**. New keywords start Active.',
                'now'   => 'Shown as a badge and used by the Status filter.',
                'later' => '—',
                'watch' => 'Status does not hide a keyword anywhere else – paused and retired keywords still appear in the Content Pipeline **Keyword list**. Paused and retired keywords drop out of the Rank Tracker.',
            ],
            [
                'field' => 'Track rank',
                'enter' => 'Tick to follow the keyword’s Google position. Ticked by default on this form. Keywords that arrive from an interest’s include terms, and imported rows with purpose interest and no track value, start unticked.',
                'now'   => 'Active ticked keywords are listed in the Rank Tracker, with positions from Search Console (when people search that exact phrase) and from imported OpenRush or Semrush results.',
                'later' => 'Rank Tracker imports keep only tracked keywords. A tracked keyword that leaves page 1 or drops sharply opens a rank_drop alert.',
                'watch' => 'Search Console positions only appear when searchers type the keyword exactly as written here, so use real search phrasing.',
            ],
            [
                'field' => 'Notes',
                'enter' => 'Optional, up to 1,000 characters. Example: where the volume figure came from, or which page should own it.',
                'now'   => 'Saved with the keyword and found by Search.',
                'later' => '—',
                'watch' => 'Reference only; nothing else reads it.',
            ],
        ],
    ],
    'keyword-import' => [
        'page'    => 'marketing-keywords',
        'form'    => 'Import CSV',
        'open'    => ['marketing-keywords', ''],
        'who'     => 'Marketing admin (Create access – needed even when the file only updates existing keywords)',
        'purpose' => 'Adds or updates many keywords at once from a spreadsheet export, for example after a keyword research session.',
        'note'    => '**Import** reads the file straight away and reports how many keywords were created, updated and skipped.',
        'fields'  => [
            [
                'field' => 'Import CSV', 'req' => true,
                'enter' => 'A .csv file with a header row. Columns: **keyword** (required), **purpose** (seo, interest or both), **priority**, **cluster**, **intent**, **volume**, **difficulty**, **notes**. A **status** column (active, paused or retired) and a **track** column (yes or no, for the Rank Tracker) are also read if present. Column order does not matter.',
                'now'   => 'Each row is matched on the keyword: new keywords are created, existing ones are updated. Rows with no keyword, or that fail to save, are counted as skipped.',
                'later' => 'Same as adding keywords by hand – they appear in the Content Pipeline **Keyword list** straight away.',
                'watch' => 'An update replaces **every** field with what is in the file: a missing or blank column resets that field (priority back to 3, purpose to SEO, status to Active; cluster, intent, volume, difficulty and notes cleared). To change one field, edit the keyword instead or export all columns first. The exception is **track**: when it is missing or blank, existing keywords keep their setting and new SEO or Both keywords are tracked. Use lower-case values (seo, active) – anything else falls back to the default. The form’s length limits are not applied: a cluster over 100, intent over 20 or notes over 1,000 characters stops the import with an error part-way, keeping the rows before it.',
            ],
        ],
    ],
    'page-add' => [
        'page'    => 'marketing-pages',
        'form'    => 'Pages → Add a page',
        'open'    => ['marketing-pages', '?tab=pages'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Adds a live nutraaxislabs.com page that the sitemaps miss, so it is crawled, checked for SEO issues and gets its Search Console and GA4 numbers like every other page.',
        'note'    => '**Add and crawl** adds the page and crawls it at once, then opens its detail screen. **Crawl site now** (top of every tab) does the full Monday job on demand: reads the sitemaps, adds published Content Pipeline pieces and recrawls every active page.',
        'fields'  => [
            [
                'field' => 'Page URL', 'req' => true,
                'enter' => 'The full address starting with https://. Example: **https://www.nutraaxislabs.com/our-story**.',
                'now'   => 'Added to the inventory as “Added by hand”, with its page type set by the type rules in Admin & Jobs → Settings, then crawled. The crawl’s findings go straight into Audit & Issues. If the page is already in the inventory it is simply recrawled (and made Active again if it was excluded).',
                'later' => 'Recrawled with every active page each Monday. Search Console and GA4 numbers are matched to it by address. Its issues feed Audit & Issues, the daily alerts and the Monday digest’s pages-with-issues list.',
                'watch' => 'Only nutraaxislabs.com pages are accepted (with or without www). Anything after a **?** and a trailing slash are ignored, so every **/our-blog?post=…** address is the same page as /our-blog – individual blog posts cannot be added. You will see “Enter a full page URL starting with https://.” if the address is incomplete.',
            ],
        ],
    ],
    'page-keyword' => [
        'page'    => 'marketing-pages',
        'form'    => 'Page detail → Add keyword',
        'open'    => ['marketing-pages', '?tab=pages'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records which search phrases a page is meant to rank for, so the Keyword map can show gaps and pages competing for the same phrase.',
        'note'    => '**Map as secondary** next to a query under Search queries adds that query as a secondary keyword (source “From search queries”); **Remove** deletes a mapping. Other buttons on this screen: **Recrawl now** crawls the page again and updates its issues; **Exclude** adds a rule for this exact path to the exclusion list in Admin & Jobs → Settings so crawls skip it and it leaves the totals; **Include in inventory** undoes that, unless a broader exclusion rule still covers the page.',
        'fields'  => [
            [
                'field' => 'Add keyword', 'req' => true,
                'enter' => 'One search phrase, up to 200 characters. Example: **berberine for metabolic health**. It is saved in lower case with extra spaces removed.',
                'now'   => 'Added to the page’s Target keywords as “Added by hand”. Linked to the Keyword Universe entry with the same wording, if there is one.',
                'later' => 'Listed on the **Keyword map** tab. Search Console queries with the same wording show as **Mapped** on Engagement & Performance → Search and drop out of the unmapped-queries list the Monday digest works from.',
                'watch' => 'You will see “That keyword is already mapped to this page.” for a repeat. This does not add the keyword to the Keyword Universe or change the page itself – the title and copy still need editing on the website.',
            ],
            [
                'field' => 'Role',
                'enter' => '**Primary** (the default) or **Secondary**.',
                'now'   => 'Saved with the mapping; primary keywords list first.',
                'later' => 'A keyword that is primary on more than one active page is flagged “Also primary on N other pages” here and “Primary on N pages” on the Keyword map.',
                'watch' => 'Give each page one primary keyword and make sure no other page uses it as primary – two pages with the same primary compete with each other in Google. To change the role, remove the keyword and add it again.',
            ],
        ],
    ],
    'issue-openrush-import' => [
        'page'    => 'marketing-issues',
        'form'    => 'Audits → Import an OpenRush audit',
        'open'    => ['marketing-issues', '?tab=audits'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Adds the result of an OpenRush site audit, run in Cursor or Claude, to Audit & Issues alongside the portal’s own crawler findings.',
        'note'    => '**Import audit** runs the import straight away. **Crawl site now** on this tab runs the portal’s crawler over every active page (the same as the Monday audit). On the **Alerts** tab, **Check now** evaluates the alert rules and emails anything new, and **Acknowledge** marks an open alert as being handled – it still resolves itself once the cause is gone.',
        'fields'  => [
            [
                'field' => 'OpenRush audit_site result (JSON)', 'req' => true,
                'enter' => 'The whole, unedited JSON reply from OpenRush’s **audit_site** tool for nutraaxislabs.com (the full reply or just its data part). Up to 2 MB.',
                'now'   => 'Audited pages are matched to the Page Inventory by address; only active pages count and the rest are skipped. Each finding is added to an issue: checks the crawler also makes (such as missing title) join the crawler’s issue, and checks only OpenRush makes (such as low content) become their own “(OpenRush)” issues. Recorded on the Audits tab as a Sample audit with OpenRush’s score.',
                'later' => 'OpenRush-only issues resolve when a later import no longer flags that page; they cannot be marked fixed or rechecked by the crawler. New high-severity issues raise the daily site-issue alert.',
                'watch' => 'Errors you may see: not valid JSON; “That is not an OpenRush audit_site result” (no pages list); an audit for another domain; or none of its pages active in the inventory (“run a crawl first”). An import never clears the crawler’s own checks – only a crawl does. Importing the same audit twice only updates the last-seen dates.',
            ],
        ],
    ],
    'issue-fixed' => [
        'page'    => 'marketing-issues',
        'form'    => 'Issue → Mark fixed and recheck',
        'open'    => ['marketing-issues', '?tab=open'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records that a problem has been fixed on the website and immediately recrawls the pages still showing it, so the portal confirms the fix rather than taking it on trust.',
        'note'    => 'Shown only for New or Open issues found by the crawler; for OpenRush-only checks, run a fresh OpenRush audit and import it instead. Other buttons: **Acknowledge** moves a New issue to Open (and out of the triage task’s count); **Recheck pages now** recrawls the open pages without marking the issue fixed; **Generate fix spec** has the AI write a developer spec from the affected pages (about 30 seconds, a few cents of AI spend) – check it before sending, as it goes into the **Developer packet**.',
        'fields'  => [
            [
                'field' => 'Fix note',
                'enter' => 'Optional, up to 2,000 characters: what was changed and by whom. Example: titles shortened in document authoring by Sam, published 3 Oct.',
                'now'   => 'Saved with the issue and shown next to “Marked fixed” with your name and the time. The issue becomes **Fixed — rechecking** and the open pages are recrawled: if none still show the problem it moves to **Verified**, otherwise back to **Open** with a “Still present on N URL(s)” note.',
                'later' => 'If a later audit finds the problem again, the issue is reopened and its reopen count goes up.',
                'watch' => 'Mark fixed only after the change is published live – the recheck runs straight away. The crawler reads each page’s HTML before browser scripts run, so a fix made only by a script may not be seen. Marking fixed again replaces the earlier note. The note is not included in the CSV export or the developer packet.',
            ],
        ],
    ],
    'issue-triage' => [
        'page'    => 'marketing-issues',
        'form'    => 'Issue → Assignee / Ignore',
        'open'    => ['marketing-issues', '?tab=open'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Says who is dealing with an issue, or sets it aside with a reason when the finding is intended (for example, account pages that should stay out of Google).',
        'note'    => '**Save assignee** saves the choice. **Ignore** moves the issue to the Ignored tab; **Stop ignoring** on an ignored issue puts it back to Open, or to Verified if no pages still have it.',
        'fields'  => [
            [
                'field' => 'Assignee',
                'enter' => 'Pick someone with Marketing update access, or **Nobody**.',
                'now'   => 'Shown on the issue and in the Assignee column of the issue lists.',
                'later' => '—',
                'watch' => 'No email or task is sent to the person – tell them. Assigning does not change the status, so the triage task in Tasks keeps counting a New issue until someone acknowledges or ignores it.',
            ],
            [
                'field' => 'Ignore because', 'req' => true,
                'enter' => 'Why the finding is fine as it is, up to 1,000 characters. Example: **account pages are meant to be noindex**.',
                'now'   => 'The issue becomes **Ignored**. The reason is shown on the issue and on the Ignored tab, with who ignored it and when.',
                'later' => 'Audits keep tracking its pages, but it stays ignored even when found on new pages, and it is left out of the open list, the high-severity site-issue alert and the legacy brand alert.',
                'watch' => 'Required – leaving it blank gives an error. Ignoring does not remove the problem from the page’s issue badges in Page Inventory or from the Monday digest’s pages-with-issues list, which come straight from the crawl. Ignore intended findings only, not work you have not got to yet.',
            ],
        ],
    ],
    'rank-import' => [
        'page'    => 'marketing-ranks',
        'form'    => 'Import → Import results',
        'open'    => ['marketing-ranks', '?tab=import'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Loads Google positions from OpenRush or Semrush for our site and competitors, so the Rank Tracker covers keywords Search Console does not report and shows who shares page 1.',
        'note'    => '**Import results** reads the data straight away and reports how many keywords, our positions and competitor positions were kept. An import can be deleted from the history (Delete access), which removes its results.',
        'fields'  => [
            [
                'field' => 'Paste results', 'req' => true,
                'enter' => 'The JSON response from OpenRush **inspect_search_visibility** (our domain or one competitor over the tracked keywords) or **inspect_serp** (one keyword; paste one response or a JSON list of them), or CSV text with **keyword**, **position** and **url** (or **domain**) columns, such as a Semrush Organic Positions export.',
                'now'   => 'Rows are matched to tracked keywords by exact wording (any case). Rows for our domain become our positions; rows for competitor domains in Settings (seo.competitor_domains) become competitor positions; every other site is dropped. A keyword checked for us but not found is kept as “not found”.',
                'later' => 'Our positions feed the Keywords tab (when Search Console has no data for the phrase), the Movers tab and the rank_drop alert. Competitor positions feed “Competitors on page 1” and the Competitors tab.',
                'watch' => 'Only 5 MB per import. OpenRush visibility results for a site other than ours or a listed competitor are refused. Untracked keywords are counted as skipped – tick Track rank in the Keyword Universe first. OpenRush checks at most 10 keywords per call when it falls back to live results; unchecked keywords are simply not in the response.',
            ],
            [
                'field' => 'Or file',
                'enter' => 'The same data as a .json or .csv file instead of pasting.',
                'now'   => 'Used instead of the pasted text when both are given.',
                'later' => '—',
                'watch' => '—',
            ],
            [
                'field' => 'Results date',
                'enter' => 'Optional date the positions were checked.',
                'now'   => 'Stamped on every result in the import.',
                'later' => 'Positions count toward the 7-day average for the week containing this date, so a wrong date moves them into the wrong comparison window.',
                'watch' => 'Blank uses the date inside the results (OpenRush fetched_at, or a CSV date column), otherwise today in UTC.',
            ],
        ],
    ],
    'backlink-import' => [
        'page'    => 'marketing-backlinks',
        'form'    => 'Import → Import',
        'open'    => ['marketing-backlinks', '?tab=import'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Loads our backlinks or the competitor link gap from OpenRush or Semrush. The type is detected from the data.',
        'note'    => '**Import** reports new and lost links, link-gap domains added, and any outreach prospects marked won.',
        'fields'  => [
            [
                'field' => 'Paste results', 'req' => true,
                'enter' => 'The JSON response from OpenRush **inspect_backlinks** for nutraaxislabs.com with the **backlinks** view, or **compare_backlink_gap** for nutraaxislabs.com against the competitors.',
                'now'   => 'Backlinks: each source page → our page pair is added or updated with anchor text, followed, spam score and first/last seen; links reported lost are marked lost. Link gap: each referring domain is added or refreshed with its authority (0–100), spam score and how many competitors it links to.',
                'later' => 'Live links from a domain in Outreach mark that prospect **Link won**. Gap domains that now link to us are marked as linking to us. Spam scores at or above backlinks.spam_threshold are flagged for the disavow list.',
                'watch' => 'Payloads for any site other than nutraaxislabs.com are refused, and links pointing at other sites are skipped. OpenRush gap rows give a competitor count but not which competitors.',
            ],
            [
                'field' => 'Or file',
                'enter' => 'A Semrush **Backlinks** export (Source url, Target url, Anchor, Nofollow, First seen, Last seen, Lost link) or **Backlink Gap** export (Domain, Authority Score and a column per site) as CSV, or an OpenRush JSON file.',
                'now'   => 'Used instead of the pasted text. For a Backlink Gap export, columns named after competitor domains in Settings give the competitor names; a column for our domain marks rows we already have.',
                'later' => 'As for pasted results.',
                'watch' => 'Semrush Backlinks exports have no spam score, so those links are never flagged as spam.',
            ],
            [
                'field' => 'Full list',
                'enter' => 'Tick only when the import is our complete live backlink list.',
                'now'   => 'Live links not in this import are marked lost with today’s date.',
                'later' => 'Lost links show a Reclaim action that adds the site to Outreach.',
                'watch' => 'Leave it unticked for partial pulls (one page of results, or a “new since” list) or every other link is marked lost. A later full import that includes them makes them live again.',
            ],
        ],
    ],
    'backlink-disavow' => [
        'page'    => 'marketing-backlinks',
        'form'    => 'Disavow → Add to disavow list',
        'open'    => ['marketing-backlinks', '?tab=disavow'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Keeps the list of spammy domains to disavow in Google Search Console. **Export disavow file** downloads it; a person uploads it in Search Console – the portal never submits it.',
        'note'    => '**Add likely-spam domains** adds every live linking domain at or above backlinks.spam_threshold in one step. **Disavow** on a Link profile row adds that one domain.',
        'fields'  => [
            [
                'field' => 'Domains', 'req' => true,
                'enter' => 'One domain per line (spaces or commas also separate them). Example: **spammy-links.example**. A full URL is reduced to its domain.',
                'now'   => 'Added to the disavow list; domains already listed, invalid ones and our own domain are skipped.',
                'later' => 'Written as **domain:example.com** lines in the exported file. The Link profile marks its links Disavowed.',
                'watch' => 'Disavowing good links can hurt rankings – list only paid-network or clearly manipulative domains. Remove a domain from the list if it was added by mistake, then re-export and re-upload.',
            ],
            [
                'field' => 'Reason',
                'enter' => 'Optional, up to 300 characters. Example: **Paid link network (PBN)**.',
                'now'   => 'Shown in the list and written as a # comment above the domain in the export.',
                'later' => '—',
                'watch' => '—',
            ],
        ],
    ],
    'prospect' => [
        'page'    => 'marketing-backlinks',
        'form'    => 'New prospect / Details and contact',
        'open'    => ['marketing-backlinks', '?tab=outreach'],
        'who'     => 'Coordinator (Create access for new, Update access to edit)',
        'purpose' => 'A site we would like a link from. Prospects are also created from the Link gap (**Add to outreach**) and from lost links (**Reclaim**).',
        'note'    => 'Open a prospect from the Outreach tab. **Add prospect** / **Save details** saves the form.',
        'fields'  => [
            [
                'field' => 'Site domain', 'req' => true,
                'enter' => 'New prospects only: the site’s domain, e.g. **functionalmedicinejournal.example**. A full URL is reduced to its domain; www. is dropped.',
                'now'   => 'Saved as the prospect. One prospect per domain.',
                'later' => 'A later backlinks import that finds a live link from this domain (or a subdomain) marks the prospect Link won.',
                'watch' => 'Our own domain and competitor domains are refused. “That domain is already a prospect.” means it is in Outreach already.',
            ],
            [
                'field' => 'Opportunity', 'req' => true,
                'enter' => 'Up to 300 characters: why this site might link to us. Example: **Resource page listing practitioner supplement brands**. Filled in for you from the Link gap or a lost link.',
                'now'   => 'Shown in the Outreach list and as the prospect’s headline.',
                'later' => 'Sent to the AI when drafting the pitch.',
                'watch' => 'Do not put the contact’s name or email here – this field goes to the AI.',
            ],
            [
                'field' => 'Our page to link to',
                'enter' => 'Choose one of our active pages from Page Inventory, or leave it for later.',
                'now'   => 'Shown in the Outreach list.',
                'later' => 'Its URL and page title are sent to the AI for the pitch. Without one, the pitch points to our home page.',
                'watch' => 'Must be a nutraaxislabs.com page.',
            ],
            [
                'field' => 'Owner',
                'enter' => 'The Marketing user doing the outreach. Defaults to you.',
                'now'   => 'Shown in the Outreach list.',
                'later' => 'Follow-up tasks are assigned to the owner.',
                'watch' => '—',
            ],
            [
                'field' => 'Contact name / Contact role / Contact email',
                'enter' => 'Optional: the person to write to (up to 150, 150 and 320 characters). Example: **Jane Doe**, **Editor**, **jane@example.com**.',
                'now'   => 'Saved on the prospect and shown to Marketing users only. The name appears in the Outreach list.',
                'later' => 'Never sent to the AI – the pitch uses [Name] for you to fill in.',
                'watch' => 'Store work contact details only, from the site itself. The email must be a valid address.',
            ],
            [
                'field' => 'Next follow-up',
                'enter' => 'The date to act next. New prospects default to today.',
                'now'   => 'Shown in the Outreach list (red when due).',
                'later' => 'On that date a task opens for the owner: send the pitch, follow up, or answer a reply. Log as sent moves it on automatically.',
                'watch' => 'Clearing it stops the task from opening.',
            ],
            [
                'field' => 'Angle',
                'enter' => 'Optional, up to 1,000 characters: why our page is useful to their readers. Also editable above the AI draft button.',
                'now'   => 'Saved on the prospect.',
                'later' => 'Sent to the AI when drafting the pitch.',
                'watch' => 'Describe what the page covers, not what a product does – the pitch must make no product claims.',
            ],
        ],
    ],
    'prospect-pitch' => [
        'page'    => 'marketing-backlinks',
        'form'    => 'Prospect → Pitch',
        'open'    => ['marketing-backlinks', '?tab=outreach'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Drafts the outreach email with AI, lets you edit it, and gives you a copy to send from your own mailbox.',
        'note'    => '**Draft pitch with AI** saves the angle and runs the Backlinks & Outreach — AI Pitch Draft job (logged in the Process Log). **Save pitch** saves your edits. **Copy** puts the subject and email on the clipboard.',
        'fields'  => [
            [
                'field' => 'Angle for the AI',
                'enter' => 'Optional: the hook for this site. Example: **New trial summary written for clinicians; their readers are practitioners**.',
                'now'   => 'Saved on the prospect when you draft.',
                'later' => 'The AI sees only the site’s domain, the opportunity, this angle and our page title and URL.',
                'watch' => 'Drafting replaces the current subject and email.',
            ],
            [
                'field' => 'Subject / Email',
                'enter' => 'The AI draft, edited as you like. It uses **[Name]**, **[Your name]** and **[LINK]** placeholders.',
                'now'   => 'The AI draft is claims-checked and its score shown above; saving your own edits clears the score.',
                'later' => 'Nothing is emailed from the portal – copy it, send it yourself, then Log as sent.',
                'watch' => 'Keep product and ingredient benefit claims out of outreach. Replace every placeholder before sending.',
            ],
        ],
    ],
    'prospect-log' => [
        'page'    => 'marketing-backlinks',
        'form'    => 'Prospect → Log outreach',
        'open'    => ['marketing-backlinks', '?tab=outreach'],
        'who'     => 'Coordinator (Update access)',
        'purpose' => 'Records each outreach step so the history, status and follow-up tasks stay right.',
        'note'    => '**Log** saves the step to the prospect’s history.',
        'fields'  => [
            [
                'field' => 'What happened', 'req' => true,
                'enter' => '**Sent** (the pitch or a follow-up), **They replied**, **Link won**, **Declined**, **Follow up on a different date**, or **Note only**. Closed prospects offer **Reopen**.',
                'now'   => 'Sent sets the status to Contacted and the next follow-up outreach.follow_up_days ahead. Replied sets Replied. Link won and Declined close the prospect and clear the follow-up. Reopen sets Contacted with a follow-up today.',
                'later' => 'Open prospects get a task when the follow-up falls due; closing one removes its task on the next task sync.',
                'watch' => 'Log a send only after you have actually sent the email.',
            ],
            [
                'field' => 'Follow-up date',
                'enter' => 'Optional date.',
                'now'   => 'Used by **They replied** (default 2 days ahead) and required by **Follow up on a different date**.',
                'later' => 'The follow-up task opens on this date.',
                'watch' => 'Ignored by the other choices.',
            ],
            [
                'field' => 'Linking page',
                'enter' => 'For Link won: the page on their site that links to us (full URL, optional).',
                'now'   => 'Saved as the won link and added to the note.',
                'later' => '—',
                'watch' => 'A later backlinks import also marks prospects won automatically when it finds their link.',
            ],
            [
                'field' => 'Note',
                'enter' => 'Optional, up to 2,000 characters. Example: **Editor asked for a shorter summary**.',
                'now'   => 'Saved in the history.',
                'later' => '—',
                'watch' => 'Required for Note only.',
            ],
        ],
    ],
];
