-- Monthly report snapshots (frozen once a month's analytics are complete), their AI highlights and review,
-- and a log of documents generated by the Output Generator and Reports.

IF OBJECT_ID('dbo.MktReport', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MktReport (
        ReportID                INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_MktReport PRIMARY KEY,
        PeriodMonth             CHAR(7)         NOT NULL,
        PeriodStart             DATE            NOT NULL,
        PeriodEnd               DATE            NOT NULL,
        DataJson                NVARCHAR(MAX)   NOT NULL,
        FrozenAt                DATETIME2(0)    NOT NULL CONSTRAINT DF_MktReport_FrozenAt DEFAULT (SYSUTCDATETIME()),
        FrozenBy                INT             NULL,
        Highlights              NVARCHAR(MAX)   NULL,
        HighlightsAt            DATETIME2(0)    NULL,
        HighlightsModel         NVARCHAR(100)   NULL,
        HighlightsPromptVersion INT             NULL,
        HighlightsCostUsd       DECIMAL(12, 6)  NULL,
        HighlightsError         NVARCHAR(1000)  NULL,
        HighlightsLogID         INT             NULL,
        ReviewedAt              DATETIME2(0)    NULL,
        ReviewedBy              INT             NULL,
        ReviewNote              NVARCHAR(1000)  NULL,
        CONSTRAINT UQ_MktReport_Month UNIQUE (PeriodMonth)
    );
END
GO

IF OBJECT_ID('dbo.MktOutputLog', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MktOutputLog (
        OutputLogID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_MktOutputLog PRIMARY KEY,
        OutputType  NVARCHAR(40)    NOT NULL,
        Format      NVARCHAR(10)    NOT NULL,
        Title       NVARCHAR(300)   NOT NULL,
        Href        NVARCHAR(500)   NOT NULL,
        UserID      INT             NULL,
        CreatedAt   DATETIME2(0)    NOT NULL CONSTRAINT DF_MktOutputLog_At DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT CK_MktOutputLog_Format CHECK (Format IN (N'print', N'docx'))
    );
    CREATE INDEX IX_MktOutputLog_CreatedAt ON dbo.MktOutputLog (CreatedAt DESC);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.MktPrompt WHERE PromptKey = N'reports.monthly_highlights')
INSERT INTO dbo.MktPrompt (PromptKey, Version, Provider, Model, SystemPrompt, UserTemplate, Temperature, MaxTokens, IsActive, Notes)
VALUES (
    N'reports.monthly_highlights', 1, N'anthropic', NULL,
    N'You write the "Highlights" section at the top of the monthly marketing report for {{brand_name}}, a practitioner-channel dietary supplement brand with a new website and small audience. Numbers are small; say so plainly and never overstate a trend from a handful of visits or clicks.

Use ONLY the numbers in the facts. Do not invent numbers, causes or comparisons that are not in the facts. When the prior period is zero or missing, say the metric is new rather than quoting a percentage. Average search position: lower is better. Do not make or repeat any health or product benefit claim.

Write 4 to 6 Markdown bullets, most important first: what grew, what fell, what stood out (a query, page, channel, keyword, link or asset), and what the team did (content, campaigns, fixes, research). Then one line starting "**Watch:**" naming the one or two things to keep an eye on next month. Each bullet is one sentence with its number.

Reply with JSON only: {"highlights": "the Markdown bullets and the Watch line"}',
    N'MONTH: {{period_label}} ({{period_start}} to {{period_end}}), compared with {{prior_label}}

FACTS (JSON):
{{facts}}',
    0.3, 2500, 1, N'Monthly report — aggregate numbers only (no contact details); written when a month is frozen.'
);
GO

MERGE dbo.MktSetting AS target
USING (VALUES
    (N'reports.freeze_after_days', N'5', N'A closed month''s report is frozen once Search Console and Analytics have data through its last day, or on this day of the next month at the latest.')
) AS source (SettingKey, SettingValue, Description)
ON target.SettingKey = source.SettingKey
WHEN NOT MATCHED THEN INSERT (SettingKey, SettingValue, Description) VALUES (source.SettingKey, source.SettingValue, source.Description);
GO

UPDATE dbo.MktSetting SET SettingValue = SettingValue + NCHAR(10) + N'report|5'
WHERE SettingKey = N'tasks.sla_days' AND SettingValue NOT LIKE N'%report|%';
GO
